verbale esterno 06_12
SWATEngineering/Docs pull request #106
Opened 2023-12-07 12:43 UTC by lonewalker0

2023-12-15 07:55 UTC, RiccardoTonioloDev commented
Questo documento sta andando avanti?

2023-12-15 09:11 UTC, lonewalker0 commented
> Questo documento sta andando avanti?

no, è finito

2023-12-15 10:45 UTC, RiccardoTonioloDev requested changes
Da correggere

2023-12-15 11:33 UTC, lonewalker0 commented
stamattina ho aggiunto 2 robette sulla parte inerente la documentazione

2023-12-16 10:32 UTC, Dovid308 requested changes

2023-12-16 10:32 UTC, Dovid308 commented on src/2_RTB/VerbaliEsterni/VerbaleEsterno_061223/content.typ
> +  - Integrazione delle funzioni movingAverage di Clickhouse;
eviterei di metterlo, forse addirittura non le introduciamo, tecnicamnte poi non sono delle funzioni di clickhouse.

2023-12-16 10:32 UTC, Dovid308 commented on src/2_RTB/VerbaliEsterni/VerbaleEsterno_061223/content.typ
> +La proponente ha anche sottolineato che l'individuazione dei casi d'uso risulta essere più complessa a causa del fatto che il sistema è quasi esclusivamente backend. In questo contesto, la natura pre
In questo contesto, la natura prevalentemente di backend potrebbe rendere più sfumata la comprensione e l'identificazione dei casi d'uso


potrebbe rendere più sfumata la comprensione?

2023-12-16 10:32 UTC, Dovid308 commented on src/2_RTB/VerbaliEsterni/VerbaleEsterno_061223/content.typ
> +Da notare che la proponente ha sottolineato la preferenza per la qualità rispetto alla quantità. In altre parole, si è manifestato un interesse più marcato verso sensori altamente efficaci e pertinen
o che include elementi superflui.
 
 
 O si toglie la frase o si allinea il tempo verbale (... o che potrebbe includere....)

2023-12-16 10:32 UTC, Dovid308 commented on src/2_RTB/VerbaliEsterni/VerbaleEsterno_061223/content.typ
> +  - Differenziazione delle onde sinusoidali dei vari sensori;
Propriamente non lo hanno chiesto.

2023-12-16 10:32 UTC, Dovid308 commented on src/2_RTB/VerbaliEsterni/VerbaleEsterno_061223/content.typ
> +  - Rinomina del nome dei sensori;
Rinonima del nome?

2023-12-16 10:32 UTC, Dovid308 commented on src/2_RTB/VerbaliEsterni/VerbaleEsterno_061223/content.typ
> +  - Accelerazione del ciclo rappresentativo della giornata;
Cambierei piuttosto in qualcosa del tipo: Visualizzazione di un maggiore lasso temporale di dati (o qualcosa del genere)

2023-12-16 10:32 UTC, Dovid308 commented on src/2_RTB/VerbaliEsterni/VerbaleEsterno_061223/content.typ
> +La Proponente ha sollevato una critica sostanziale in merito alla comprensibilità della dashboard, evidenziando la difficoltà di interpretare il grafico sinusoidale a causa della sovrapposizione di d
"accelerando il ciclo per rappresentare una "giornata" in pochi minuti e aumentare il tasso di generazione dei dati per una rappresentazione più dinamica" 

non credo che sia una soluzione alla sovrapposizione dei dati.

2023-12-16 14:39 UTC, lonewalker0 commented on src/2_RTB/VerbaliEsterni/VerbaleEsterno_061223/content.typ
> +  - Rinomina del nome dei sensori;
uuid avevamo prima

2023-12-16 14:42 UTC, lonewalker0 commented on src/2_RTB/VerbaliEsterni/VerbaleEsterno_061223/content.typ
> +  - Differenziazione delle onde sinusoidali dei vari sensori;
differenziare i sensori nel modo in cui generano l’onda sarebbe

2023-12-17 10:01 UTC, Dovid308 submitted a review, later dismissed
per quanto riguarda gli obbiettivi dello sprint quasi quasi andrei anche a togliere l'elenco puntato.

2023-12-17 10:01 UTC, Dovid308 commented on src/2_RTB/VerbaliEsterni/VerbaleEsterno_061223/content.typ
> -In seguito, la riunione ha proseguito con una dettagliata discussione riguardo la parte inerente la documentazione, ponendo particolare enfasi sull'Analisi dei Requisiti.
refuso proseguito -> proseguita

2023-12-17 10:03 UTC, Dovid308 commented on src/2_RTB/VerbaliEsterni/VerbaleEsterno_061223/content.typ
> -In seguito, la riunione ha proseguito con una dettagliata discussione riguardo la parte inerente la documentazione, ponendo particolare enfasi sull'Analisi dei Requisiti.
nella versione aggiornata *

2023-12-18 07:46 UTC, RiccardoTonioloDev requested changes
Se non dovesse essere aggiunto altro in futuro, ma solo corretto quanto richiesto, diventa un LGTM.

2023-12-18 07:46 UTC, RiccardoTonioloDev commented on src/2_RTB/VerbaliEsterni/VerbaleEsterno_061223/content.typ
> +Nell'incontro con la Proponente, il team ha illustrato in dettaglio l'evoluzione del Proof of Concept, evidenziandone gli importanti progressi compiuti nel corso dello sprint. La Proponente ha manife
Aggiungere spazio tra ".Inoltre".

2023-12-18 07:46 UTC, RiccardoTonioloDev commented on src/2_RTB/VerbaliEsterni/VerbaleEsterno_061223/content.typ
> +Gli obiettivi prefissati comprendevano l'archiviazione dei dati provenienti da Kafka nel database OLAP ClickHouse, nonché lo sviluppo di una dashboard in Grafana. La dashboard avrebbe dovuto visualiz
```suggestion
Gli obiettivi prefissati comprendevano l'archiviazione dei dati provenienti da Kafka nel database OLAP ClickHouse, nonché lo sviluppo di una dashboard in Grafana. La dashboard avrebbe dovuto visualizzare una mappa della città indicando la posizione dei sensori di temperatura, presentare in modo chiaro le temperature medie rilevate e un grafico che mostrasse l'andamento sinusoidale della temperatura.
```

2023-12-18 07:46 UTC, RiccardoTonioloDev commented on src/2_RTB/VerbaliEsterni/VerbaleEsterno_061223/content.typ
> +La Proponente ha sollevato una critica sostanziale in merito alla comprensibilità della dashboard, evidenziando la difficoltà di interpretare il grafico sinusoidale a causa della sovrapposizione di d
```suggestion
La Proponente ha sollevato una critica sostanziale in merito alla comprensibilità della dashboard, evidenziando la difficoltà di interpretare il grafico sinusoidale a causa della sovrapposizione di dati. La soluzione proposta è quella di rendere le temperature più singolari e differenziare il modo in cui i sensori generano l'onda sinusoidale, accelerando il ciclo per rappresentare una "giornata" in pochi minuti, aumentando il tasso di generazione dei dati per una rappresentazione più dinamica. È stato inoltre consigliato di aggiungere un pannello descrittivo.
```

2023-12-18 07:46 UTC, RiccardoTonioloDev commented on src/2_RTB/VerbaliEsterni/VerbaleEsterno_061223/content.typ
> +La proponente risultava essere soddisfatta anche della nuova versione dell'Analisi dei Requisiti, l'unica perplessità riguardava il numero complessivo della tipoliogia di sensori, ritenuto eccessivam
```suggestion
La proponente risultava essere soddisfatta anche della nuova versione dell'Analisi dei Requisiti. L'unica perplessità riguardava il numero complessivo della tipologia di sensori, ritenuto eccessivamente elevato anche in termini di visualizzazione sulla dashboard, e alcuni casi d'uso considerati ridondanti. 
```

2023-12-18 07:55 UTC, RiccardoTonioloDev approved these changes
LGTM

2023-12-18 07:57 UTC, merged