94 update NdP
SWATEngineering/Docs pull request #124
Opened 2023-12-08 16:39 UTC by nance97

close #103 close #94 close #95

2023-12-09 19:18 UTC, lonewalker0 requested changes

2023-12-09 19:18 UTC, lonewalker0 commented on src/2_RTB/NormeDiProgetto/content.typ
> +Eventuali variazioni nella distribuzione dei ruoli, rispetto alla pianificazione iniziale, vengono documentate e giustificate nel Consuntivo del Piano di Progetto. Questo approccio consente al team d
```suggestion
Eventuali variazioni nella distribuzione dei ruoli, rispetto alla pianificazione iniziale, vengono documentate e giustificate nel Consuntivo del _Piano di Progetto_. Questo approccio consente al team di adattarsi in modo flessibile alle esigenze emergenti, mantenendo costantemente un quadro chiaro delle variazioni e delle ragioni che sottendono a tali modifiche.
```

2023-12-09 19:18 UTC, lonewalker0 commented on src/2_RTB/NormeDiProgetto/content.typ
>  Durante il periodo di sviluppo del progetto, ogni membro assumerà 6 ruoli distinti con compiti diversificati, al fine di garantire una gestione completa ed efficace delle diverse fasi e aspetti del l
```suggestion
Durante il periodo di sviluppo del progetto, ciascun membro assume 6 ruoli distinti, con compiti diversificati, al fine di garantire una gestione completa ed efficace delle diverse fasi e aspetti del lavoro. Questi ruoli contribuiscono a promuovere la collaborazione sinergica e l'ottimizzazione delle risorse all'interno del team.
```

valuta se mettere il 6 in lettere o in numero

2023-12-09 19:18 UTC, lonewalker0 commented on src/2_RTB/NormeDiProgetto/content.typ
>          - Stesura del documento Analisi dei Requisiti;
```suggestion
        - Stesura del documento _Analisi dei Requisiti_;
```

2023-12-09 19:18 UTC, lonewalker0 commented on src/2_RTB/NormeDiProgetto/content.typ
>          - Redazione della Specifica tecnica e di una parte del documento Piano di Qualifica.
```suggestion
        - Redazione del documento _Specifiche Tecniche_ e di una parte del documento _Piano di Qualifica_.
```

2023-12-09 19:18 UTC, lonewalker0 commented on src/2_RTB/NormeDiProgetto/content.typ
>          - Realizzazione del Manuale Utente;
```suggestion
        - Realizzazione del _Manuale Utente_;
```

anche sopra dove si parla delle specifiche tecniche mantieni la stessa formattazione

2023-12-09 19:18 UTC, lonewalker0 commented on src/2_RTB/NormeDiProgetto/content.typ
>  Per fare in modo che ogni membro svolga almeno 1 volta tutti i ruoli di cui sopra, il team si impegna a cambiarli ogni settimana.
```suggestion
Per garantire che ogni membro svolga almeno una volta tutti i ruoli menzionati, il team si impegna a cambiarli ogni settimana.
```

2023-12-09 19:18 UTC, lonewalker0 commented on src/2_RTB/NormeDiProgetto/content.typ
> +                + Pianificazione attività per la settimana (valutate rispetto a quanto pianificato nel Piano di Progetto) e assegnazione issue.
```suggestion
                + Pianificazione attività per la settimana (valutate rispetto a quanto pianificato nel _Piano di Progetto_) e assegnazione issue.
```

2023-12-09 19:18 UTC, lonewalker0 commented on src/2_RTB/NormeDiProgetto/content.typ
>  Negli incontri esterni i partecipanti sono i membri del team e i referenti della Proponente. Questi incontri sono pianificati ogni due settimane in concomitanza con l'inizio e fine sprint. Durante qu
```suggestion
Negli incontri esterni i partecipanti includono i membri del team e i referenti della Proponente. Questi incontri sono pianificati ogni due settimane in concomitanza con l'inizio e fine sprint. Durante queste sessioni, i partecipanti del team hanno l'opportunità di presentare gli sviluppi recenti, condividere i progressi raggiunti e discutere eventuali sfide o questioni emerse nel corso del lavoro. 
```

abbiamo cambiato la durata degli sprint

2023-12-09 19:18 UTC, lonewalker0 commented on src/2_RTB/NormeDiProgetto/content.typ
>  Inoltre si possono richiedere incontri di formazione specifici su particolari tecnologie, il che offre al team l'opportunità di approfondire la comprensione di una tecnologia specifica, imparare le _
```suggestion
In aggiunta, è possibile richiedere sessioni di formazione mirate su tecnologie specifiche, offrendo al team l'opportunità di approfondire la comprensione di una particolare tecnologia, imparare le _best practice_ e acquisire competenze più avanzate.
```

2023-12-12 11:28 UTC, lonewalker0 requested changes

2023-12-12 11:28 UTC, lonewalker0 commented on src/2_RTB/NormeDiProgetto/content.typ
> +Software per creare diagrammi e grafici di varia natura, utilizzato dagli Analisti per creare i diagrammi UML dei casi d'uso nella sezione *Casi d'uso* dell'Analisi dei Requisiti.
```suggestion
Software per creare diagrammi e grafici di varia natura, utilizzato dagli Analisti per creare i diagrammi UML dei casi d'uso nella sezione *Casi d'uso* (@c.uso) dell'Analisi dei Requisiti.
```

2023-12-12 11:28 UTC, lonewalker0 commented on src/2_RTB/NormeDiProgetto/content.typ
> +==== Identificazione dei casi d'uso
```suggestion
==== Identificazione dei casi d'uso <c.uso>
```

2023-12-12 11:28 UTC, lonewalker0 commented on src/2_RTB/NormeDiProgetto/content.typ
> +La fase di progettazione segue l'analisi dei requisiti, dove sono definite le necessità e le aspettative per il prodotto. I Progettisti traducono queste informazioni in una struttura architteturale d
```suggestion
La fase di progettazione segue l'analisi dei requisiti, dove sono definite le necessità e le aspettative per il prodotto. I Progettisti traducono queste informazioni in una struttura architetturale definita, organizzando il sistema in componenti specifici e definendo le interazioni tra di essi. In questo modo, la progettazione costituisce un passo essenziale nel percorso di sviluppo, contribuendo a trasformare i requisiti in un piano tangibile per la creazione del prodotto finale.
```

2023-12-12 11:28 UTC, lonewalker0 commented on src/2_RTB/NormeDiProgetto/content.typ
> +                - *scelte tecnologiche*: consiste nello stabilire quali tecnologie adottare per lo sviluppo del Poc, anche su consiglio della Proponente.
metterei il maiuscolo per rispettare la formattazione

2023-12-13 08:30 UTC, nance97 commented on src/2_RTB/NormeDiProgetto/content.typ
> +                - *scelte tecnologiche*: consiste nello stabilire quali tecnologie adottare per lo sviluppo del Poc, anche su consiglio della Proponente.
io no perche' non e' giustificato, usiamo il maiuscolo solo per le lettere che compaiono in acronimi come Proof of Concept per PoC e altro.

2023-12-13 12:05 UTC, lonewalker0 requested changes

2023-12-13 12:05 UTC, lonewalker0 commented on src/2_RTB/NormeDiProgetto/content.typ
> +        - *LCM*: Linee di Codice per Metodo.
```suggestion
     #table(
      columns:(auto,auto,auto),
      align: (x, y) => (center, center, center).at(x),
      fill:(_,row) =>if row==0 {luma(150)} else if calc.odd(row) { luma(220)} else {white},
      [*Metrica*],[*Descrizione*],[*Riferimento*],
      [*SFIN*],[Structure Fan In],[@me_q_prodotto],
      [*SFOUT*],[Structure Fan Out],[@me_q_prodotto],
      [*ATC*],[Attributi per Classe],[@me_q_prodotto],
      [*PM*],[Parametri per Metodo],[@me_q_prodotto],
      [*LCM*],[Linee di Codice per Metodo],[@me_q_prodotto]
      
)
```

2023-12-13 12:05 UTC, lonewalker0 commented on src/2_RTB/NormeDiProgetto/content.typ
> +        - *ROPS*: Requisiti Opzionali Soddisfatti.
```suggestion
       #table(
      columns:(auto,auto,auto),
      align: (x, y) => (center, center, center).at(x),
      fill:(_,row) =>if row==0 {luma(150)} else if calc.odd(row) { luma(220)} else {white},
      [*Metrica*],[*Descrizione*],[*Riferimenti*],
      [*ROS*],[Requisiti Obbligatori Soddisfatti],[@me_q_prodotto],
      [*RDS*],[Requisiti Desiderabili Soddisfatti],[@me_q_prodotto],
      [*ROPS*],[Requisiti Opzionali Soddisfatti],[@me_q_prodotto]  
)
```

2023-12-14 17:14 UTC, nance97 commented on src/2_RTB/NormeDiProgetto/content.typ
> +        - *MBC*: branch coverage.
sono vecchie, nel senso che le avevo inserite qui ma poi non nelle metriche vere e proprie nell'ultima sezione perchè non ero sicura fossero rilevanti/facilmente calcolabili. secondo te dovrei tenerle e definirle giù?

2023-12-15 15:26 UTC, nance97 commented
@lonewalker0 vediamo di chiudere questa pull request il prima possibile così da chiudere anche un po' di issues connesse e sgomberare la kanban board; dubito che toccherò nuovamente le NdP in settimana.

2023-12-15 21:28 UTC, lonewalker0 submitted a review, later dismissed

2023-12-17 14:38 UTC, merged