101 restructuring adr from the ground up
SWATEngineering/Docs pull request #125
Opened 2023-12-09 16:56 UTC by nance97

2023-12-12 10:19 UTC, RiccardoTonioloDev requested changes
Il codice per la costruzione delle tabelle dei requisiti è corretto.

Il codice per la costruzione delle tabelle di tracciamento è sbagliato, poiché si deve associare il codice del vincolo alla fonte corrispondente, invece viene erroneamente dato lo stato come primo campo (ovvero Obbligatorio, Desiderabile, Opzionale). Da cambiare di modo che usi il codice nella prima colonna.

Non avendo poi il codice come prima colonna, anche l'ultimo script per la creazione della tabella di conteggio riassuntiva fallisce, determinando una tabella popolata da zeri.

2023-12-12 14:20 UTC, ranghetto commented
> Il codice per la costruzione delle tabelle dei requisiti è corretto.
> 
> 
> 
> Il codice per la costruzione delle tabelle di tracciamento è sbagliato, poiché si deve associare il codice del vincolo alla fonte corrispondente, invece viene erroneamente dato lo stato come primo campo (ovvero Obbligatorio, Desiderabile, Opzionale). Da cambiare di modo che usi il codice nella prima colonna.
> 
> 
> 
> Non avendo poi il codice come prima colonna, anche l'ultimo script per la creazione della tabella di conteggio riassuntiva fallisce, determinando una tabella popolata da zeri.

Grazie non lo avevo notato, in giornata sistemo

2023-12-12 21:07 UTC, RiccardoTonioloDev commented
> @RiccardoTonioloDev per quanto riguarda gli UC da UC10: Inserimento dati temperatura in poi [quelli che hanno il sensore come attore principale], pensi sia sensato ricavarne dei requisiti funzionali? se si', come dovrei formattarli: l'utente deve poter visualizzare dati relativi alla temperatura?

Secondo me si. Il requisito è che il sistema deve poter essere in grado di immagazzinare e processare dati relativi alla temperatura (nel caso della temperatura). Non sono sicuro fino a che livello di dettaglio si debba andare (nel senso, anche il come devono essere messi in storage? come devono essere ricevuti? in che formato?).
Sicuramente è da approfondire con il prof, però, assolutamente si, bisogna trarne dei requisiti.

2023-12-12 21:07 UTC, RiccardoTonioloDev commented
Ragazzi se la pr è in draft non mettetelo in ready to review. Ora la sposto.

2023-12-13 15:25 UTC, lonewalker0 commented on src/2_RTB/AnalisiDeiRequisiti/changelog.csv
> +1.0,08-12-2023,Rimozione use cases extra e aggiunta UML individuali,Nancy Kalaj,Analista
```suggestion
0.10,08-12-2023,Rimozione use cases extra e aggiunta UML individuali,Nancy Kalaj,Analista
```

2023-12-14 17:55 UTC, nance97 commented on src/2_RTB/AnalisiDeiRequisiti/content.typ
> +- *Postcondizioni*: l'attore visualizza un pannello contenente dati relativi alla velocità e alla direzione del vento, in chilometri orari, su di una mappa, che mostra delle frecce direzionate e colo
bella domanda, penso che intendessero quello? dubito che tutti i grafici a mappa sfruttino l'unica mappa che abbiamo al momento nella parte inferiore della dashboard, anche se potrebbero, penso che piuttosto si aprirà un nuovo pannello ma bisognerebbe chiedere.

2023-12-14 21:03 UTC, ranghetto commented
My 50 cents as an administrator: questo branch e' aperto da 2 settimane, e' arrivato il momento di chiuderlo il prima possibile e lavorare con issues piu' piccole.

2023-12-15 08:21 UTC, RiccardoTonioloDev requested changes
Aggiungere un #pagebreak() (funzione typst per rimandare all'inizio di una nuova pagina) prima di ogni sezione di requisiti, e prima della tabella finale riassuntiva dei requisiti.

2023-12-15 08:21 UTC, RiccardoTonioloDev commented on src/2_RTB/AnalisiDeiRequisiti/content.typ
>  = Requisiti
Ci sono due sezioni "Requisiti". Tenere solo quella in fondo al documento.

2023-12-17 14:48 UTC, merged