Aggiunta sezione relativa ai diagrammi UML per i casi d'uso, nelle norme di progetto, con relative immagini.
SWATEngineering/Docs pull request #131
Opened 2023-12-12 14:14 UTC by RiccardoTonioloDev

close #122

2023-12-12 18:27 UTC, lonewalker0 requested changes

2023-12-12 18:27 UTC, lonewalker0 commented on src/2_RTB/NormeDiProgetto/content.typ
> +                        - *Precondizioni*: stato in cui il sistema si deve trovare prima che la funzionalità rappresentata dal caso d'uso venga iniziata;
```suggestion
                        - *Precondizioni*: stato in cui il sistema si deve trovare prima dell'avvio della funzionalità rappresentata dal caso d'uso ;
```

2023-12-12 18:27 UTC, lonewalker0 commented on src/2_RTB/NormeDiProgetto/content.typ
> +                        - *Postcondizioni*: stato in cui il sistema si troverà una volta compiuta la funzionalità rappresentata dal caso d'uso;
```suggestion
                        - *Postcondizioni*: stato in cui il sistema si troverà dopo aver completato la funzionalità rappresentata dal caso d'uso;
```

2023-12-12 18:27 UTC, lonewalker0 commented on src/2_RTB/NormeDiProgetto/content.typ
> +                Ciascun caso d'uso sarà connesso attraverso una linea continua agli attori che hanno autorizzazioni per accedere a quella particolare funzione.
```suggestion
                Ciascun caso d'uso è connesso, attraverso una linea continua, agli attori che hanno autorizzazioni per accedere a quella particolare funzione.
```

2023-12-12 18:27 UTC, lonewalker0 commented on src/2_RTB/NormeDiProgetto/content.typ
> +        - *Estensioni*: Supponiamo che nell'ambito dei diagrammi dei casi d'uso UML, l'estensione rappresenti una connessione tra due casi d'uso, A e B, indicando che ogni istanza del caso d'uso A pu
```suggestion
        - *Estensioni*: nel contesto dei diagrammi dei casi d'uso UML, la relazione di estensione indica una connessione tra due casi d'uso, A e B, segnalando che ogni istanza del caso d'uso A può condizionalmente eseguire anche il caso d'uso B. L'esecuzione del caso d'uso B avviene soltanto in specifiche circostanze o sotto condizioni particolari durante l'esecuzione del caso d'uso A, interrompendo temporaneamente il flusso del caso d'uso A. La responsabilità dell'esecuzione del caso d'uso esteso (B) ricade su chi estende (nel caso, il caso d'uso B). Questa relazione viene visualizzata graficamente con una freccia tratteggiata dal caso d'uso esteso (B) al caso d'uso base (A), con l'etichetta "extend".
```

2023-12-12 18:27 UTC, lonewalker0 commented on src/2_RTB/NormeDiProgetto/content.typ
> +        - *Inclusioni*: Supponiamo che vi sia una relazione di inclusione tra un caso d'uso A e un caso d'uso B se ogni istanza del caso d'uso A deve necessariamente eseguire le istanze del caso d'us
```suggestion
        - *Inclusioni*: supponiamo che vi sia una relazione di inclusione tra un caso d'uso A e un caso d'uso B se ogni istanza del caso d'uso A deve necessariamente eseguire le istanze del caso d'uso B. Questo assegna al caso d'uso A la responsabilità di eseguire il caso d'uso B, eliminando la duplicazione e favorendo il riutilizzo di una struttura comune. La connessione di inclusione viene simboleggiata da una freccia tratteggiata che collega il caso d'uso A a tutti i casi d'uso inclusi, come nel caso del caso d'uso B nell'esempio. Sopra la freccia verrà annotata la direttiva "include".
```

2023-12-12 21:12 UTC, RiccardoTonioloDev commented on src/2_RTB/NormeDiProgetto/content.typ
> +                A livello di diagramma, l'attore viene rappresentato come un omino stilizzato, identificabile mediante un'etichetta univoca e rappresentativa, al disotto di tale figura.
Ho solo corretto "al di sotto" con "al disotto" (ho cercato su internet), il resto mi va bene, ora committo.

2023-12-12 21:16 UTC, RiccardoTonioloDev commented on src/2_RTB/NormeDiProgetto/content.typ
> +                        - *Postcondizioni*: stato in cui il sistema si troverà una volta compiuta la funzionalità rappresentata dal caso d'uso;
Cambio con:
```suggestion
                        - *Postcondizioni*: stato in cui il sistema si troverà dopo che l'utente avrà portato a termine lo scopo rappresentato dal caso d'uso;
```

2023-12-12 21:21 UTC, RiccardoTonioloDev commented on src/2_RTB/NormeDiProgetto/content.typ
> +                        - *Attore principale*: l'attore che desidera compiere lo scopo rappresentato dal caso d'uso;
cambio solo desidera con intende perchè lo trovo appropriato (ma rappresentato mi piace di più per dare l'idea che il caso d'uso rappresenti appunto uno scopo).

2023-12-12 22:14 UTC, RiccardoTonioloDev commented
@lonewalker0 ho aggiunto un bel po' di termini nel glossario per riuscire a risolvere anche la issue #132 poiché altrimenti dopo il rebase la gh action non mi faceva più proseguire.

2023-12-13 09:47 UTC, lonewalker0 requested changes

2023-12-13 09:47 UTC, lonewalker0 commented on src/2_RTB/Glossario/terms.csv
> +Sprint backlog; Lo Sprint Backlog è una lista di compiti specifici che il team di sviluppo ha pianificato per un singolo Sprint in Scrum. Questa lista deriva direttamente dagli elementi prioritari de
```suggestion
Sprint backlog; Lo Sprint Backlog è una lista di compiti specifici che il team di sviluppo ha pianificato per un singolo Sprint in Scrum. Questa lista deriva direttamente dagli elementi prioritari del Product Backlog, selezionati per essere affrontati durante lo Sprint. In modo conciso, lo Sprint Backlog è una sorta di "to-do list", contenente le attività che il team si impegna a completare durante uno specifico periodo di Sprint,  di solito con una durata fissata (come due o quattro settimane). Durante lo Sprint Planning Meeting, il team seleziona gli elementi prioritari dal Product Backlog, li suddivide in compiti più piccoli, e li inserisce nello Sprint Backlog. Lo Sprint Backlog è dinamico e può essere adattato durante lo Sprint, ma una volta iniziato lo Sprint, la lista rimane stabile senza l'aggiunta di nuovi elementi. L'obiettivo è consegnare un incremento di prodotto funzionante alla fine di ogni Sprint.
```

2023-12-13 09:47 UTC, lonewalker0 commented on src/2_RTB/Glossario/terms.csv
> +Design patterns; I design patterns (modelli di progettazione) nell'ambito del software engineering sono soluzioni ricorrenti a problemi comuni che si presentano durante la progettazione del software.
```suggestion
Design patterns; I design patterns (modelli di progettazione) nell'ambito del software engineering sono soluzioni ricorrenti a problemi comuni che si presentano durante la progettazione del software. Questi pattern forniscono un approccio collaudato e riconosciuto per affrontare situazioni specifiche, offrendo una guida ai progettisti e sviluppatori nel risolvere problemi ricorrenti in modo efficiente e robusto. Essi fungono da astrazioni di alto livello che catturano le migliori pratiche per la progettazione di software, promuovendo la riusabilità del codice, la manutenibilità e la scalabilità del sistema. 
```


la definizione era già stata scritta sopra ma questa mi sembra migliore

2023-12-13 09:47 UTC, lonewalker0 commented on src/2_RTB/Glossario/terms.csv
> +Rebase workflow; Il workflow di rebase in GitHub è una pratica che coinvolge la riorganizzazione della storia di un branch prima di integrarlo nel branch principale (solitamente "main" o "master"). I
```suggestion
Rebase workflow; Il workflow di rebase in GitHub è una pratica che coinvolge la riorganizzazione della storia di un branch prima di integrarlo nel branch principale (solitamente "main" o "master"). Invece di unire direttamente i cambiamenti, come avviene con un merge, il rebase riscrive la storia del branch, applicando ogni singolo commit uno dopo l'altro nel branch di destinazione. Questo processo  crea una storia più lineare e pulita, poiché i commit del branch di funzione sembreranno essere stati sviluppati direttamente sulla cima del branch principale. 
```

2023-12-13 09:47 UTC, lonewalker0 commented on src/2_RTB/Glossario/terms.csv
> +Requirements and technology baseline; Nel contesto dell'ingegneria del software è una fase iniziale e fondamentale del processo di sviluppo del software. In questa fase, l'obiettivo principale è stab
```suggestion
Requirements and technology baseline; Nel contesto dell'ingegneria del software è una fase iniziale e fondamentale del processo di sviluppo del software. In questa fase, l'obiettivo principale è stabilire e comprendere i requisiti del sistema e definire la base tecnologica sulla quale il progetto si svilupperà. Le tre principali attività di questa fase sono: l'analisi dei requisiti, la definizione della baseline tecnologica e la definizione della baseline di progetto.
```

2023-12-13 09:47 UTC, lonewalker0 commented on src/2_RTB/Glossario/terms.csv
> +Customer acceptance; È l'ultima fase del ciclo di vita del software e coinvolge la presentazione del prodotto finito al cliente per valutazione e approvazione. Durante questa fase, il cliente esamina
```suggestion
Customer acceptance; È l'ultima fase del ciclo di vita del software, coinvolgendo la presentazione del prodotto finito al cliente per valutazione e approvazione. Durante questa fase, il cliente esamina attentamente il software rispetto ai requisiti concordati e alle aspettative iniziali. I test di accettazione vengono eseguiti per garantire che il prodotto soddisfi le specifiche richieste. L'obiettivo è ottenere l'approvazione del cliente e la consegna del prodotto in un ambiente operativo. Una volta accettato dal cliente, il software è pronto per l'utilizzo e la distribuzione.
```

2023-12-13 09:47 UTC, lonewalker0 commented on src/2_RTB/Glossario/terms.csv
> +Milestone; Rappresenta un punto chiave o un traguardo significativo nel corso di un progetto. Si tratta di un evento temporale specifico che indica il completamento di una fase importante, l'implemen
```suggestion
Milestone; Rappresenta un punto chiave o un traguardo significativo nel corso di un progetto. Si tratta di un evento temporale specifico che indica il completamento di una fase importante, l'implementazione di una funzionalità critica, o il raggiungimento di un obiettivo prestabilito. Le milestone sono utilizzate per valutare il progresso del progetto, sincronizzare le attività del team e fornire punti di riferimento per la pianificazione temporale complessiva. Spesso, le milestone sono associate a risultati tangibili o decisioni cruciali che influenzano il percorso futuro del progetto.
```

2023-12-13 09:47 UTC, lonewalker0 commented on src/2_RTB/Glossario/terms.csv
> +Context switch; All'interno di un team di sviluppo del software, si riferisce al problema che sorge quando i membri del team devono cambiare improvvisamente il loro focus da un compito a un altro o d
```suggestion
Context switch; All'interno di un team di sviluppo del software, si riferisce al problema che sorge quando i membri del team devono cambiare improvvisamente il loro focus da un compito o una responsabilità a un altro. Questo fenomeno è spesso causato da una rotazione frequente dei ruoli all'interno del team.
```

2023-12-13 09:47 UTC, lonewalker0 commented on src/2_RTB/Glossario/terms.csv
> +Topic; In Apache Kafka, un "topic" è una categoria o una suddivisione logica dei dati che consente di organizzare e suddividere i flussi di messaggi. I topic sono fondamentali nel modello di pubblica
```suggestion
Topic; In Apache Kafka, un "topic" è una categoria o una suddivisione logica dei dati che consente di organizzare e suddividere i flussi di messaggi. I topic sono fondamentali nel modello di pubblicazione/sottoscrizione di Kafka, dove i produttori inviano messaggi a specifici topic e i consumatori si sottoscrivono a tali topic per ricevere i messaggi di loro interesse. I topic sono scalabili e flessibili, consentendo l'implementazione di soluzioni distribuite e la gestione efficiente di grandi volumi di dati in tempo reale.
```

2023-12-13 12:13 UTC, RiccardoTonioloDev commented on src/2_RTB/Glossario/terms.csv
> +Topic; In Apache Kafka, un "topic" è una categoria o una suddivisione logica dei dati che consente di organizzare e suddividere i flussi di messaggi. I topic sono fondamentali nel modello di pubblica
Secondo me non serve come aggiunta. Anche perché non sono una cosa fatta da noi. Ci sta così com'è, ovvero una breve descrizione di come funzionano in Kafka. Poi rischiamo anche di usare termini sbagliati.

2023-12-13 13:54 UTC, lonewalker0 approved these changes

2023-12-13 14:03 UTC, lonewalker0 approved these changes

2023-12-13 15:38 UTC, Dovid308 submitted a review, later dismissed

2023-12-13 16:04 UTC, Dovid308 submitted a review, later dismissed
lgtm

2023-12-13 16:06 UTC, lonewalker0 submitted a review, later dismissed
fine

2023-12-13 16:08 UTC, Dovid308 approved these changes

2023-12-13 16:14 UTC, merged