116 pdp consuntivo
SWATEngineering/Docs pull request #142
Opened 2023-12-15 17:03 UTC by simocare

2023-12-15 17:05 UTC, simocare commented
Ci sono ancora da correggere i dati, perché sono appena stati correti, mi interessa una review sugli script per calcolare le ore.

2023-12-15 19:44 UTC, lonewalker0 requested changes
- [x] per quanto riguarda lo script basta cambiare la dimensione delle tabelle
- [ ] nel consuntivo del primo sprint mi sono dimenticato di mettere i valori del tempo speso e quello rimanente
- [ ]  gli aerogrammi del preventivo ho sbagliato a mettere il tipo di grafico: doveva essere quello in 3d

2023-12-15 21:27 UTC, lonewalker0 approved these changes

2023-12-15 21:42 UTC, lonewalker0 requested changes

2023-12-15 21:42 UTC, lonewalker0 commented on src/2_RTB/PianoDiProgetto/sections/ConsuntivoSprint/SecondoSprint.typ
> +Il consuntivo relativo al corrente sprint evidenzia significative disparità rispetto al preventivo, soprattutto in merito alla distribuzione dei ruoli. Tale deviazione è imputabile al cambiamento dei
```suggestion
Il consuntivo, relativo allo sprint corrente, evidenzia significative disparità rispetto al preventivo, soprattutto in merito alla distribuzione dei ruoli. Tale deviazione è imputabile al cambiamento dei ruoli assegnati, avvenuto a metà sprint, circostanza non prevista durante la fase di pianificazione iniziale. Inoltre, va sottolineato che la conclusione delle attività pendenti dallo sprint precedente, ha determinato brevi periodi di tempo in cui i membri del team hanno mantenuto i ruoli assegnati nella fase precedente.  Nonostante un aumento complessivo delle ore e dei costi, va notato che tali incrementi non risultano eccessivi. Emergono chiaramente, in particolare, una sovrastima delle ore necessarie per il ruolo di Programmatore e una sottostima per il ruolo di Analista. Queste considerazioni verranno utilizzate come base per ottimizzare la pianificazione degli sprint futuri.
```

2023-12-16 08:58 UTC, simocare commented
> * [ ]  per quanto riguarda lo script basta cambiare la dimensione delle tabelle
> 
>     * [ ]  nel consuntivo del primo sprint mi sono dimenticato di mettere i valori del tempo speso e quello rimanente
> 
>     * [ ]   gli aerogrammi del preventivo ho sbagliato a mettere il tipo di grafico: doveva essere quello in 3d

Conviene aprire un'altra issue per modificare il consuntivo del primo sprint.

2023-12-16 09:26 UTC, simocare commented
Visti i nuovi dati sono cambiate anche le considerazioni nell'analisi a posteriori, quindi richiede una review.

2023-12-17 07:53 UTC, lonewalker0 requested changes

2023-12-17 07:53 UTC, lonewalker0 commented on src/2_RTB/PianoDiProgetto/sections/ConsuntivoSprint/SecondoSprint.typ
> +Il consuntivo, relativo allo sprint corrente, evidenzia significative disparità rispetto al preventivo, soprattutto in merito alla distribuzione dei ruoli. Tale deviazione è imputabile al cambiamento
motiverei il perché in più delle ore da analista

2023-12-17 10:17 UTC, lonewalker0 requested changes

2023-12-17 10:17 UTC, lonewalker0 commented on src/2_RTB/PianoDiProgetto/sections/ConsuntivoSprint/SecondoSprint.typ
> +Il consuntivo, relativo allo sprint corrente, evidenzia significative disparità rispetto al preventivo, soprattutto in merito alla distribuzione dei ruoli. Tale deviazione è imputabile al cambiamento
```suggestion
Il consuntivo, relativo allo sprint corrente, evidenzia significative disparità rispetto al preventivo, soprattutto in merito alla distribuzione dei ruoli. Tale deviazione è imputabile al cambiamento dei ruoli assegnati, avvenuto a metà sprint, circostanza non prevista durante la fase di pianificazione iniziale. Inoltre, va sottolineato che la conclusione delle attività pendenti dallo sprint precedente, ha determinato brevi periodi di tempo in cui i membri del team hanno mantenuto i ruoli assegnati nella fase precedente. Dato il considerevole aumento complessivo delle ore rispetto a quanto inizialmente previsto nel preventivo, diventa essenziale adottare un approccio più attento nella fase di pianificazione e apportare gli adeguamenti necessari ai futuri preventivi. In particolare, emerge una sottostima delle ore necessarie per il ruolo di Analista. Ciò è dovuto al fatto che, nel corso di questo sprint, il team si è focalizzato sulla stesura dell'_Analisi dei Requisiti_ e sulla sua ristrutturazione, intervenuta dopo il colloquio con il professor Cardin e la discussione con la Proponente. Queste considerazioni verranno utilizzate come base per ottimizzare la pianificazione degli sprint futuri.
```

invertirei questa frase:
" Ciò è dovuto al fatto che, nel corso di questo sprint, il team si è focalizzato sulla stesura dell'_Analisi dei Requisiti_ e sulla sua ristrutturazione, intervenuta dopo il colloquio con il professor Cardin e la discussione con la Proponente." 

in
"il team, dopo il colloquio con il prof cardin ........ Proponente, si è focalizzato sulla ...."

2023-12-17 11:51 UTC, lonewalker0 requested changes
c'è qualcosa che non va sui diagrammi del secondo sprint

2023-12-17 14:10 UTC, lonewalker0 approved these changes

2023-12-17 14:11 UTC, merged