Miglioramento intro PdQ e aggiunti riferimenti
SWATEngineering/Docs pull request #151
Opened 2023-12-18 17:50 UTC by ranghetto

2023-12-19 16:37 UTC, Dovid308 approved these changes
Si potrebbe inserire la sezione relativa al glossario prima dei riferimenti che vedo esserci in tutti i nostri documenti, tra l'altro forse non hai aggiornato il changelog

2023-12-19 16:37 UTC, Dovid308 commented on src/2_RTB/PianoDiQualifica/content.typ
> +Infine, è orientato al miglioramento costante: si adatta in base alle esperienze acquisite e a eventuali modifiche richieste nel progetto, garantendo così che il processo e il prodotto crescano e si
frase non felicissima specie l'ultima parte ma puo andare lo stesso

2023-12-19 16:40 UTC, Dovid308 requested changes
okay non volevo approvare prima

2023-12-20 08:22 UTC, ranghetto commented on src/2_RTB/PianoDiQualifica/content.typ
> +Infine, è orientato al miglioramento costante: si adatta in base alle esperienze acquisite e a eventuali modifiche richieste nel progetto, garantendo così che il processo e il prodotto crescano e si
Cosa non e' chiaro?

2023-12-20 12:57 UTC, Dovid308 commented on src/2_RTB/PianoDiQualifica/content.typ
> +Infine, è orientato al miglioramento costante: si adatta in base alle esperienze acquisite e a eventuali modifiche richieste nel progetto, garantendo così che il processo e il prodotto crescano e si
ribadisco può andare lo stesso, non mi piaceva la forma, ma alla fine dei conti è corretto, approvo

2023-12-20 13:01 UTC, Dovid308 approved these changes
lgtm

2023-12-20 13:14 UTC, merged