Stesura verbale interno 15-12-23
SWATEngineering/Docs pull request #152
Opened 2023-12-18 18:20 UTC by ranghetto

2023-12-19 14:50 UTC, lonewalker0 requested changes

2023-12-19 14:50 UTC, lonewalker0 commented on src/2_RTB/VerbaliInterni/VerbaleInterno_151223/content.typ
> +Una proposta significativa è emersa per gestire le attività in modo più efficiente: creare issue man mano che emergono le necessità, facendo anche tutto il lavoro di assegnazione della priorità, dell
```suggestion
È emersa una proposta significativa  per la gestione delle attività con maggior efficienza: creare issue al manifestarsi delle necessità, svolgendo anche tutto il lavoro di assegnazione delle priorità, delle grandezze, sia durante le riunioni, che durante gli stand-up. Inoltre è stato creato il nuovo tag "Ruolo" all'interno delle issue al fine di agevolare coloro responsabili di quella attività.  La decisione è stata accolta positivamente dai partecipanti, che hanno visto in questa pratica un modo per ottimizzare il tempo durante le riunioni.
```

2023-12-19 14:50 UTC, lonewalker0 commented on src/2_RTB/VerbaliInterni/VerbaleInterno_151223/content.typ
> +La tecnologia "Pydantic" per il linguaggio Python è stata riconosciuta come parte integrante per l'MVP, in modo da semplificare la verifica e la validazione del software.
```suggestion
La tecnologia "Pydantic" per il linguaggio Python è stata riconosciuta come parte integrante per l'MVP, in modo da semplificare la verifica e la validazione del software, anche attraverso l'ampio uso di type hints, facilitando la dichiarazione e l'uso di tipi di dati all'interno del codice.
```

2023-12-19 14:50 UTC, lonewalker0 commented on src/2_RTB/VerbaliInterni/VerbaleInterno_151223/content.typ
> +Altra decisione è stata quella di adottare una assegnazione delle ore in multipli di trenta minuti (0.5 h), all'interno del foglio condiviso di time tracking, con l'obiettivo di evitare complicazioni
```suggestion
È stata presa un'alltra significativa decisione riguardo l'adozione dell'assegnazione delle ore in multipli di trenta minuti (0.5 h), all'interno del foglio condiviso di time tracking, con l'obiettivo di evitare complicazioni non necessarie e garantire una gestione più precisa del tempo.
```

2023-12-19 14:50 UTC, lonewalker0 commented on src/2_RTB/VerbaliInterni/VerbaleInterno_151223/content.typ
> +A questo si collega uno sviluppo di una automazione in grado di aggiornare il Piano di Progetto secondo quanto svolto dal team durante gli sprint. Oltre che a far risparmiare tempo ai responabili e a
```suggestion
A questo si collega lo sviluppo di un' automazione in grado di aggiornare il _Piano di Progetto v1.0_ secondo quanto svolto dal team durante gli sprint. Oltre a far risparmiare tempo ai Responabili e agli Amministratori, questo script comporterà un notevole vantaggio in termini di sicurezza nell'elaborazione dei calcoli del consuntivo.
```

2023-12-19 14:50 UTC, lonewalker0 commented on src/2_RTB/VerbaliInterni/VerbaleInterno_151223/content.typ
> +Una discussione approfondita ha riguardato la terminologia utilizzata nei documenti, con un consenso raggiunto sul termine "Verificatore" anziché "Revisore".
```suggestion
Una discussione è stata condotta per esaminare la terminologia utilizzata nei documenti, e si è raggiunto un consenso sull'adozione del termine "Verificatore" anzichè "Revisore",.
```

boh non mi ricordo la motivazione

2023-12-19 14:50 UTC, lonewalker0 commented on src/2_RTB/VerbaliInterni/VerbaleInterno_151223/content.typ
> +Infine, sono state decise modifiche significative riguardanti la durata dello sprint, riducendola da due a una settimana, per adattarsi meglio alla flessibilià richiesta in questo periodo e al ritmo
non serve metterlo era già stato deciso, al posto di questo puoi mettere che abbiamo deciso come metodo l'inspection al posto del walktoghghghgh

2023-12-20 08:34 UTC, ranghetto commented on src/2_RTB/VerbaliInterni/VerbaleInterno_151223/content.typ
> +A questo si collega uno sviluppo di una automazione in grado di aggiornare il Piano di Progetto secondo quanto svolto dal team durante gli sprint. Oltre che a far risparmiare tempo ai responabili e a
Non abbiamo un piano di progetto v1 (?)

2023-12-20 08:38 UTC, ranghetto commented on src/2_RTB/VerbaliInterni/VerbaleInterno_151223/content.typ
> +Infine, sono state decise modifiche significative riguardanti la durata dello sprint, riducendola da due a una settimana, per adattarsi meglio alla flessibilià richiesta in questo periodo e al ritmo
Lo scriviamo gia' nel PdP

2023-12-20 13:47 UTC, lonewalker0 requested changes

2023-12-20 13:47 UTC, lonewalker0 commented on src/2_RTB/VerbaliInterni/VerbaleInterno_151223/content.typ
> +È emersa una proposta significativa è emersa per la gestione delle attività con maggior efficienza: creare issue al manifestarsi delle necessità, svolgendo anche tutto il lavoro di assegnazione delle
```suggestion
È emersa una proposta significativa per la gestione delle attività con maggior efficienza: creare issue al manifestarsi delle necessità, svolgendo anche tutto il lavoro di assegnazione delle priorità, delle grandezze, sia durante le riunioni, sia durante gli stand-up. Inoltre è stato creato il nuovo tag "Ruolo" all'interno delle issue al fine di agevolare coloro responsabili di quella attività. La decisione è stata accolta positivamente dai partecipanti, che hanno visto in questa pratica un modo per ottimizzare il tempo durante le riunioni.
```

2023-12-20 13:54 UTC, lonewalker0 approved these changes

2023-12-20 13:55 UTC, merged