158 issueona pdp
SWATEngineering/Docs pull request #172
Opened 2023-12-31 09:25 UTC by ranghetto

2024-01-02 20:30 UTC, nance97 requested changes

2024-01-02 20:30 UTC, nance97 commented on src/2_RTB/PianoDiProgetto/sections/ConsuntivoSprint/QuartoSprint.typ
> +Rimane dentro al budjet il consuntivo che ci porta sempre più vicini alla revisione RTB.
```suggestion
Rimane dentro al budget il consuntivo che ci porta sempre più vicini alla revisione RTB.
```

2024-01-02 20:30 UTC, nance97 commented on src/2_RTB/PianoDiProgetto/sections/ConsuntivoSprint/TerzoSprint.typ
> +Il terzo sprint viene accorciato ad una settimana, per questo il totale delle ore è minore rispetto agli sprint precedenti. All'inizio si pensava di essere in grado di consegnare un prodotto ed una d
```suggestion
Il terzo sprint viene accorciato ad una settimana, per questo il totale delle ore è minore rispetto agli sprint precedenti. All'inizio si pensava di essere in grado di ultimare una versione del #glossary[PoC] e completare la documentazione pertinente in modo da sostenere la revisione RTB verso la fine di questo sprint, ma ciò non è stato possibile; per questo abbiamo investito il tempo extra per migliorare l'automazione nella stesura dei documenti, il che spiega perché sono state dedicate molte ore al ruolo di Amministratore.
```
ho messo PoC glossariato perchè è termine di glossario, ma dobbiamo stabilire se marcarlo con la function ad ogni occorrenza

2024-01-02 20:30 UTC, nance97 commented on src/2_RTB/PianoDiProgetto/sections/Pianificazione.typ
> +Si programma di sviluppare in _Proof of Concept_ (POC) del progetto secondo le indicazioni della _Proponente_, che sia in grado di veficare la coesione dello stack tecnologico, i suoi punti di forza
```suggestion
Si programma di sviluppare il _Proof of Concept_ (POC) del progetto secondo le indicazioni della Proponente, il cui feedback è fondamentale per verificare la coesione dello stack tecnologico, i suoi punti di forza e le sue carenze.
```

2024-01-02 20:30 UTC, nance97 commented on src/2_RTB/PianoDiProgetto/sections/Pianificazione.typ
> +Durante questa fase il colloquio con la _Proponente_ e il _Committente_ viene mantenuto costante, in questo modo, e grazie anche alle conoscenze acquisite dalla costruzione del POC,sarà possibile ada
```suggestion
Durante questa fase il colloquio con la _Proponente_ e il _Committente_ viene mantenuto costante; in questo modo, e grazie anche alle conoscenze acquisite dalla costruzione del POC, sarà possibile adattare e migliorare l'_Analisi dei Requisiti_.
```
il corsivo viene usato per dare importanza ai termini? se è così eviterei perchè al momento non è normato/utilizzato altrove con questa accezione

2024-01-02 20:30 UTC, nance97 commented on src/2_RTB/PianoDiProgetto/sections/Pianificazione.typ
> +Attraverso le fasi di progettazione e sviluppo ha inizio la creazione del progetto vero e proprio, utilizzando le conoscenze acquisitie durante la creazione del POC. Lo sviluppo al suo interno conter
```suggestion
Attraverso le fasi di progettazione e sviluppo ha inizio la creazione del progetto vero e proprio, utilizzando le conoscenze acquisite durante la creazione del POC. Lo sviluppo includerà anche le fasi di testing del prodotto.
```

2024-01-03 12:19 UTC, Dovid308 commented
Non vuole essere un review voglio solo avere un po di contesto: 
comunque queste parole sono in formato da glossario

File analizzato: ./src/2_RTB/PianoDiProgetto/functions.typ
Termini con formato errato:
sprint

File analizzato: ./src/2_RTB/PianoDiProgetto/sections/Consuntivo.typ
Termini con formato errato:
sprint

File analizzato: ./src/2_RTB/PianoDiProgetto/sections/Preventivo.typ
Termini con formato errato:
sprint

File analizzato: ./src/2_RTB/PianoDiProgetto/sections/Introduzione.typ
Termini con formato errato:
baseline

File analizzato: ./src/2_RTB/PianoDiProgetto/sections/AnalisiDeiRischi.typ
Termini con formato errato:
framework
sistema
poc
documentazione
architettura
its
sprint

File analizzato: ./src/2_RTB/PianoDiProgetto/sections/Pianificazione.typ
Termini con formato errato:
poc
documentazione
architettura
customer acceptance
sprint
product baseline
requirements and technology baseline
bug

File analizzato: ./src/2_RTB/PianoDiProgetto/sections/ModelloDiSviluppo.typ
Termini con formato errato:
framework
daily scrum
framework scrum
sprint

File analizzato: ./src/2_RTB/PianoDiProgetto/sections/PreventivoSprint/PrimoSprint.typ
Termini con formato errato:
requirements and technology baseline
baseline
milestone

File analizzato: ./src/2_RTB/PianoDiProgetto/sections/PreventivoSprint/TerzoSprint.typ
Termini con formato errato:
milestone
customer acceptance

File analizzato: ./src/2_RTB/PianoDiProgetto/sections/PreventivoSprint/SecondoSprint.typ
Termini con formato errato:
product baseline
baseline
milestone

File analizzato: ./src/2_RTB/PianoDiProgetto/sections/ConsuntivoSprint/PrimoSprint.typ
Termini con formato errato:
sprint

File analizzato: ./src/2_RTB/PianoDiProgetto/sections/ConsuntivoSprint/TerzoSprint.typ
Termini con formato errato:
documentazione
sprint

File analizzato: ./src/2_RTB/PianoDiProgetto/sections/ConsuntivoSprint/QuartoSprint.typ
Termini con formato errato:
sprint

File analizzato: ./src/2_RTB/PianoDiProgetto/sections/ConsuntivoSprint/SecondoSprint.typ
Termini con formato errato:
sprint

2024-01-05 07:47 UTC, nance97 commented
Nel meeting di ieri 04/01 si è deciso di preservare pianificazione e preventivo per sprint, per cui mi occuperò di reinserire le sezioni apposite per i primi 6 sprint e per i 2 sprint successivi visto che vogliamo pianificare a breve termine (2 sprint in avanti); integrerò anche i cambiamenti richiesti sopra per la parte di testo pertinente alle 3 revisioni.

2024-01-08 22:02 UTC, nance97 commented
- [ ] riaggiungere pianificazione per sprint fino al settimo;
- [ ] riaggiungere preventivo per sprint (dopo aver automatizzato la creazione di tabelle e grafici come per il consuntivo);
- [ ] aggiungere consuntivi 5 e 6 e maggior dettaglio ai precedenti.

2024-01-10 21:00 UTC, simocare requested changes

2024-01-10 21:03 UTC, simocare commented on src/2_RTB/PianoDiProgetto/sections/PianificazioneSprint/TerzoSprint.typ
> +    - Implementare ed utilizzare la funzionalità di filtraggio propria di Grafana.
Sarebbe da rimuovere ogni volta in cui si dice "rotazione ruoli" perché non è priamente una rotazione.
Inoltre sarebbe utile inserire l'intervallo dello sprint (data inizio data fine) anche nei consuntivi, per migliorarne la leggibilità.
Al massimo lo farà il prossimo responsabile.

2024-01-12 20:36 UTC, nance97 commented on src/2_RTB/PianoDiProgetto/sections/ConsuntivoSprint/PrimoSprint.typ
> +    - È stato effettuato anche un incontro di _workshop_ interno incentrato su _Docker Compose_ in cui i componenti che avevano già utilizzato tale tecnologia ne hanno illustrato scopo e funzionament
Da quel che ho visto lo script per il consuntivo prende la settimana dallo spreadsheet Time & Resource Manager e ne deriva lo sprint corrispondente, quindi non viene tenuta in considerazione la settimana venerdì-venerdì ma quella tradizionale.

2024-01-12 20:53 UTC, nance97 commented on src/2_RTB/PianoDiProgetto/sections/ConsuntivoSprint/QuintoSprint.typ
> +  - L'Ordine del giorno non è stato realizzato in quanto non è stato svolto un incontro interno al termine dello #glossary[sprint] vista la mancanza di disponibilità di vari componenti del team negli
Lo capisco ma vorrei fare riferimento all'ordine del giorno esplicitamente perché è una delle misure preventive contro RC1 citate sopra in Analisi dei rischi.

2024-01-13 15:56 UTC, simocare commented on src/2_RTB/PianoDiProgetto/sections/ConsuntivoSprint/PrimoSprint.typ
> +    - È stato effettuato anche un incontro di _workshop_ interno incentrato su _Docker Compose_ in cui i componenti che avevano già utilizzato tale tecnologia ne hanno illustrato scopo e funzionament
Si infatti è effettivamente un problema nel conteggio delle ore che dovremo risolvere. Comunque prima vediamo di risolvere quello, poi correggiamo anche qui eventualmente.

2024-01-15 23:36 UTC, lonewalker0 requested changes
per il momento questi

2024-01-15 23:36 UTC, lonewalker0 commented on src/2_RTB/PianoDiProgetto/sections/AnalisiDeiRischi.typ
>    - *Valutazione*:  Pericolosità: media; Occorrenza: media.
```suggestion
  - *Valutazione*:  Pericolosità: media; Occorrenza: media;
```

2024-01-15 23:36 UTC, lonewalker0 commented on src/2_RTB/PianoDiProgetto/sections/AnalisiDeiRischi.typ
>      - Continuo _refactoring_: integrare  all'interno del processo di sviluppo frequenti attività di _refactoring_ mirate alla semplificazione del codice, in modo tale da aumentarne la comprensibilità
```suggestion
    - Continuo refactoring: integrare  all'interno del processo di sviluppo frequenti attività di refactoring mirate alla semplificazione del codice, in modo tale da aumentarne la comprensibilità;
```

2024-01-15 23:36 UTC, lonewalker0 commented on src/2_RTB/PianoDiProgetto/sections/AnalisiDeiRischi.typ
>  == Rischi di Comunicazione
togliere i ** dal titolo

2024-01-15 23:36 UTC, lonewalker0 commented on src/2_RTB/PianoDiProgetto/sections/AnalisiDeiRischi.typ
>    - *Identificazione*: questo rischio si manifesta quando non esiste una struttura chiara per la comunicazione all'interno del team, può essere riconosciuto attraverso il sovrapporsi di messaggi, dis
```suggestion
  - *Identificazione*: questo rischio si manifesta quando non esiste una struttura chiara per la comunicazione all'interno del team, può essere riconosciuto attraverso il sovrapporsi di messaggi, discussioni disordinate o mancanza di canali dedicati;
```

2024-01-15 23:36 UTC, lonewalker0 commented on src/2_RTB/PianoDiProgetto/sections/AnalisiDeiRischi.typ
>    - *Valutazione*: Pericolosità: bassa; Occorrenza: bassa.
```suggestion
  - *Valutazione*: Pericolosità: bassa; Occorrenza: bassa;
```

2024-01-15 23:36 UTC, lonewalker0 commented on src/2_RTB/PianoDiProgetto/sections/AnalisiDeiRischi.typ
> +    - Pianificazione della comunicazione: stabilire canali di comunicazione specifici per diversi tipi di messaggi (ad esempio discussioni generali, questioni urgenti, cambiamenti dello stato delle _
```suggestion
    - Pianificazione della comunicazione: stabilire canali di comunicazione specifici per diversi tipi di messaggi (ad esempio discussioni generali, questioni urgenti, cambiamenti dello stato delle issue nell'#glossary[ITS], proposte per l'ordine del giorno e altro);
```

2024-01-15 23:36 UTC, lonewalker0 commented on src/2_RTB/PianoDiProgetto/sections/AnalisiDeiRischi.typ
>  === *RC2 - Esasperazione di conflitti interni*
```suggestion
=== RC2 - Esasperazione di conflitti interni
```

2024-01-15 23:36 UTC, lonewalker0 commented on src/2_RTB/PianoDiProgetto/sections/AnalisiDeiRischi.typ
>  Questi rischi emergono quando diversi punti di vista, preferenze o approcci all'interno del team conducono a tensioni, disaccordi o scontri tra i membri. Questi conflitti possono manifestarsi in vari
mettere le ';' alla fine, anche nel prossimo rischio

2024-01-15 23:36 UTC, lonewalker0 commented on src/2_RTB/PianoDiProgetto/sections/AnalisiDeiRischi.typ
>      - Aggiornamenti regolari: mantenere la Proponente informata sugli sviluppi in modo regolare (almeno una volta alla settimana) e chiedere _feedback_ quando necessario;
```suggestion
    - Aggiornamenti regolari: mantenere la Proponente informata sugli sviluppi in modo regolare (almeno una volta alla settimana) e chiedere feedback quando necessario;
```

2024-01-15 23:36 UTC, lonewalker0 commented on src/2_RTB/PianoDiProgetto/sections/AnalisiDeiRischi.typ
> +    - Consegna anticipata di materiale: quando si tratta di _Sprint retrospective_ o di qualsiasi revisione congiunta, fornire la #glossary[documentazione] o il codice prodotto nel rispettivo #glossa
```suggestion
    - Consegna anticipata di materiale: quando si tratta di #glossary[Sprint retrospective] o di qualsiasi revisione congiunta, fornire la #glossary[documentazione] o il codice prodotto nel rispettivo #glossary[sprint] il prima possibile, in modo che la Proponente abbia tempo sufficiente per esaminarlo in modo approfondito prima del meeting. Ciò permette una discussione più efficace e informativa durante il meeting stesso.
```

2024-01-15 23:36 UTC, lonewalker0 commented on src/2_RTB/PianoDiProgetto/sections/AnalisiDeiRischi.typ
>  === *RC4 - Mancanza di fiducia*
```suggestion
=== RC4 - Mancanza di fiducia
```

2024-01-15 23:36 UTC, lonewalker0 commented on src/2_RTB/PianoDiProgetto/sections/AnalisiDeiRischi.typ
>    - *Valutazione*: Pericolosità: media; Occorrenza: bassa.
```suggestion
  - *Valutazione*: Pericolosità: media; Occorrenza: bassa;
```

2024-01-15 23:36 UTC, lonewalker0 commented on src/2_RTB/PianoDiProgetto/sections/AnalisiDeiRischi.typ
>  === *RC5 - Context Switch*
```suggestion
=== RC5 - Context Switch
```

2024-01-15 23:36 UTC, lonewalker0 commented on src/2_RTB/PianoDiProgetto/sections/AnalisiDeiRischi.typ
>  === *RP1 - Comprensione erronea dei requisiti*
```suggestion
=== RP1 - Comprensione erronea dei requisiti
```

2024-01-15 23:36 UTC, lonewalker0 commented on src/2_RTB/PianoDiProgetto/sections/AnalisiDeiRischi.typ
>  La comprensione erronea dei requisiti indica il potenziale malinteso o fraintendimento dei requisiti del progetto, che potrebbe portare a interpretazioni errate o divergenti da parte del team riguard
nei punti sotto mancano i ';'

2024-01-15 23:36 UTC, lonewalker0 commented on src/2_RTB/PianoDiProgetto/sections/AnalisiDeiRischi.typ
> +    - Test di integrazione preliminare: condurre test preliminari di integrazione delle componenti principali in una fase iniziale del progetto. Questi test aiutano a valutare la compatibilità e l'in
```suggestion
    - Test di integrazione preliminari: condurre test preliminari di integrazione delle componenti principali nella fase iniziale del progetto. Questi test aiutano a valutare la compatibilità e l'interoperabilità delle varie parti, riducendo così il rischio di disallineamento nell'#glossary[architettura] finale.
```

2024-01-15 23:36 UTC, lonewalker0 commented on src/2_RTB/PianoDiProgetto/sections/AnalisiDeiRischi.typ
>      - Rendicontazione di ore produttive: si utilizza uno _spreadsheet_ dedicato nel quale ciascun membro del team registra quotidianamente le ore produttive utilizzate, specificando le attività svolt
```suggestion
    - Rendicontazione di ore produttive: si utilizza uno #glossary[spreadsheet] dedicato nel quale ciascun membro del team registra quotidianamente le ore produttive utilizzate, specificando le attività svolte e il ruolo assunto. Questo approccio consente di trarre conclusioni riguardo allo stato delle ore totali impiegate e al budget iniziale disponibile, permettendo una migliore gestione delle risorse nel progetto;
```

2024-01-15 23:36 UTC, lonewalker0 commented on src/2_RTB/PianoDiProgetto/sections/AnalisiDeiRischi.typ
> +    - Monitoraggio Costante: si mantiene un monitoraggio costante del progresso del progetto, permettendo l'aggiornamento della pianificazione in caso di variazioni significative. In particolare, all
```suggestion
    - Monitoraggio costante: si mantiene un monitoraggio costante del progresso del progetto, permettendo l'aggiornamento della pianificazione in caso di variazioni significative. In particolare, all'interno dell'#glossary[ITS] si effettua un costante aggiornamento delle date di inizio e fine per ogni _issue_, riflettendo con precisione le tempistiche effettive. Inoltre, si utilizza regolarmente la vista Gantt all'interno della Kanban Board del progetto in GitHub per visualizzare la pianificazione temporale e individuare potenziali variazioni o sovrapposizioni nelle attività pianificate.
```

2024-01-15 23:36 UTC, lonewalker0 commented on src/2_RTB/PianoDiProgetto/sections/AnalisiDeiRischi.typ
>  === *RP4 - Impegni universitari*
```suggestion
=== RP4 - Impegni universitari
```

2024-01-15 23:36 UTC, lonewalker0 commented on src/2_RTB/PianoDiProgetto/sections/AnalisiDeiRischi.typ
> +  - *Valutazione*: Pericolosità: alta; Occorrenza: media.
```suggestion
  - *Valutazione*: Pericolosità: alta; Occorrenza: media;
```

2024-01-15 23:36 UTC, lonewalker0 commented on src/2_RTB/PianoDiProgetto/sections/AnalisiDeiRischi.typ
>  == Tabella riassuntiva
l'occorrenza nell'ultimo da modificare

2024-01-15 23:36 UTC, lonewalker0 commented on src/2_RTB/PianoDiProgetto/sections/ModelloDiSviluppo.typ
>  Il team ha deciso di adottare il modello di sviluppo agile Scrum come approccio principale per la gestione e lo sviluppo del progetto. Tale metodologia promuove un'approccio adattativo, permettendo l
```suggestion
Il team ha deciso di adottare il modello di sviluppo agile Scrum come approccio principale per la gestione e lo sviluppo del progetto. Tale metodologia promuove un'approccio adattativo, permettendo l'evoluzione dei requisiti e una ridefinizione costante del perimetro del progetto. Il modello assicura anche feedback regolari, consentendo adattamenti rapidi, riducendo gli sprechi e garantendo la soddisfazione degli obiettivi individuati dalla Proponente a ogni iterazione.
```

2024-01-15 23:36 UTC, lonewalker0 commented on src/2_RTB/PianoDiProgetto/sections/ModelloDiSviluppo.typ
> +- *Sprint*: Durante questo periodo, il team pianifica, sviluppa, testa e completa una quantità concordata di lavoro, consegnando un risultato tangibile alla fine di ogni #glossary[sprint]. Questa lun
```suggestion
- *#glossary[Sprint]*: Durante questo periodo, il team pianifica, sviluppa, testa e completa una quantità concordata di lavoro, consegnando un risultato tangibile alla fine di ogni #glossary[sprint]. Questa lunghezza di tempo è stata considerata ottimale per completare le attività previste per lo #glossary[sprint], offrendo un equilibrio tra un periodo abbastanza breve da mantenere un allineamento frequente con la Proponente, e un periodo sufficientemente lungo da permettere lo sviluppo di un incremento di lavoro utilizzabile.
```
boh aggiungerei che è settimanale

2024-01-15 23:36 UTC, lonewalker0 commented on src/2_RTB/PianoDiProgetto/sections/ModelloDiSviluppo.typ
> +- *Sprint Planning*: durante questa fase, il team identifica le #glossary("user stories") del #glossary("Product Backlog") che si impegna a completare, tenendo conto della capacità e delle risorse di
attività lavorative suona brutto,  prova a cambiare con 'da svolgere', una roba simile

2024-01-15 23:36 UTC, lonewalker0 commented on src/2_RTB/PianoDiProgetto/sections/ModelloDiSviluppo.typ
>  Non ci si concetra sul prodotto ma piuttosto sul _way of working_.
```suggestion
Non ci si concetra sul prodotto ma piuttosto sul #glossary[way of working]. 
```

2024-01-15 23:36 UTC, lonewalker0 commented on src/2_RTB/PianoDiProgetto/sections/ModelloDiSviluppo.typ
>  == Vantaggi nell'Adozione di Scrum
il corsivo da feedback è da togliere

2024-01-16 10:04 UTC, lonewalker0 requested changes
i punti e virgola negli elenchi nn vengono visualizzati nel pdf se l'ultima parola è da glossario, non so perché.

Penso li consideri caratteri di fine istruzione del glossario, prova a mettere un carattere di escape davanti tipo "\"

2024-01-16 10:04 UTC, lonewalker0 commented on src/2_RTB/PianoDiProgetto/sections/ConsuntivoSprint/SecondoSprint.typ
> +Ciononostante, il team ha portato a termine gli obiettivi prefissati nei tempi previsti, aggiungendo una pianificazione a lungo termine (fino alla CA) al _Piano di Progetto_, ultimando una prima rist
```suggestion
Ciononostante, il team ha portato a termine gli obiettivi prefissati nei tempi previsti, aggiungendo una pianificazione a lungo termine (fino alla CA) al _Piano di Progetto_, ultimando una prima ristesura dei casi d'uso nell'_Analisi dei Requisiti_ e ultimando anche una prima versione funzionante del #glossary["PoC"]. Oltre al rischio citato sopra, l'unico altro rischio degno di nota è nuovamente RT1 o "Conoscenza tecnologica limitata"; per contrastarlo è stato scelto l'approccio di lavoro in coppia, decidendo di assegnare le attività relative allo sviluppo del #glossary["PoC"] a due Programmatori che hanno lavorato sinergisticamente e spesso in modalità sincrona per unire le loro conoscenze e velocizzare la terminazione della prima versione.
```

2024-01-16 10:04 UTC, lonewalker0 commented on src/2_RTB/PianoDiProgetto/sections/ConsuntivoSprint/TerzoSprint.typ
> +L'adozione di nuove automazioni per redigere i documenti ha inizialmente portato all'emergere del rischio RT2 o Difficoltà nell'adozione degli strumenti di gestione del progetto; tuttavia, l'inclusio
```suggestion
L'adozione di nuove automazioni per redigere i documenti ha inizialmente portato l'emergere del rischio RT2 o Difficoltà nell'adozione degli strumenti di gestione del progetto; tuttavia, l'inclusione di contenuti procedurali e non solo narrativi o descrittivi all'interno delle _Norme di Progetto v1.0_ ha abilitato il team ad utilizzare il documento come riferimento in caso di dubbi e a seguire le procedure dettagliate al suo interno, utilizzando le automazioni come prescritto. La seconda misura preventiva, ossia l'inclusione di dubbi nell'#glossary[ordine del giorno] degli incontri interni, non è stata particolarmente utilizzata per dare voce a dubbi sull'utilizzo degli strumenti di gestione; si è rivelato più efficacie semplicemente chiedere informazioni e chiarimenti al componente del team che aveva precedentemente implementato e predisposto tali strumenti.  
```

2024-01-17 08:29 UTC, ranghetto commented
> i punti e virgola negli elenchi nn vengono visualizzati nel pdf se l'ultima parola è da glossario, non so perché.

Penso li consideri caratteri di fine istruzione del glossario, prova a mettere un carattere di escape davanti tipo "\"

2024-01-19 19:58 UTC, nance97 commented on src/2_RTB/PianoDiProgetto/sections/AnalisiDeiRischi.typ
>  Il team potrebbe incontrare sfide nell'apprendere l'utilizzo e nell'integrazione dei nuovi strumenti di gestione del progetto, causando ritardi nell'effettiva implementazione di un #glossary("Way of
direi maschile

2024-01-19 20:16 UTC, nance97 commented on src/2_RTB/PianoDiProgetto/sections/AnalisiDeiRischi.typ
>  == Tabella riassuntiva
cioè rimettere ad alta? è che si intende per lo più la sessione e quella è una sola

2024-01-19 21:21 UTC, nance97 commented
- [ ] menzionare inserimento dati pertinenti a sprint 7,8 nel PdQ nella pianificazione;
- [ ] immettere preventivi sprint 9,10;
- [ ] rifare il preventivo (ancora) per tentare di modificare il rapporto ore senza sforare gli 11070;
- [ ] aggiornare diagrammi di Gantt.

2024-01-21 18:53 UTC, merged