165 verbale esterno 21/12/23"
SWATEngineering/Docs pull request #181
Opened 2024-01-10 17:41 UTC by nance97

Reverts SWATEngineering/Docs#180

2024-01-10 18:17 UTC, lonewalker0 requested changes

2024-01-10 18:17 UTC, lonewalker0 commented on src/2_RTB/VerbaliEsterni/VerbaleEsterno_211223/content.typ
> -L'incontro si è aperto con la valutazione delle migliore apportate al #glossary[PoC]; in particolare, il team ha dimostrato l'utilizzo della funzione aggregata "movingAverage" propria di ClickHouse p
- migliorie
- clickhouse non ha una funzione propria di movingaverage, ci arrivi attraverso le finestre mobili 
- modifiche apportate

2024-01-10 18:17 UTC, lonewalker0 commented on src/2_RTB/VerbaliEsterni/VerbaleEsterno_211223/content.typ
> -  - Aggiunta di altre tipologie di sensori per incrementare l'impatto visivo della #glossary[dashboard].
ma lhanno detto?

2024-01-10 18:17 UTC, lonewalker0 commented on src/2_RTB/VerbaliEsterni/VerbaleEsterno_211223/content.typ
> -Il team ha voluto esprimere un dubbio riguardo all'inclusione di una stima dell'ordine di grandezza dei dati in grado di essere gestiti dal sistema all'interno dell'_Analisi dei Requisiti_; in rispos
analisi requisiti v1.0

2024-01-10 18:17 UTC, lonewalker0 commented on src/2_RTB/VerbaliEsterni/VerbaleEsterno_211223/content.typ
> -  - Rendere la #glossary[dashboard] più movimentata restringendo l'intervallo temporale di visualizzazione dei dati: in particolare, è stato suggerito di impostare un intervallo di tempo ridotto all'
movimentata -> dinamica

2024-01-10 18:17 UTC, lonewalker0 commented on src/2_RTB/VerbaliEsterni/VerbaleEsterno_211223/content.typ
> -  - Motivare la scelta di utilizzare Grafana per un progetto che prevede event-driven visualization: Grafana si basa su un refresh molto rapido dei singoli grafici della #glossary[dashboard] (anche o
poiché si concentrano maggiormente sulle aggregazioni e sull'analisi dei dati rispetto alla loro visualizzazione in real time;

2024-01-10 18:17 UTC, lonewalker0 commented on src/2_RTB/VerbaliEsterni/VerbaleEsterno_211223/content.typ
> -  - Motivare la scelta di utilizzare ClickHouse per l'elaborazione di dati di tipo #glossary[time series]: nonostante ClickHouse sia un motore OLAP, esso viene spesso utilizzato anche per gestire dat
numerosità -> moli

2024-01-11 13:00 UTC, nance97 commented on src/2_RTB/VerbaliEsterni/VerbaleEsterno_211223/content.typ
> -  - Aggiunta di altre tipologie di sensori per incrementare l'impatto visivo della #glossary[dashboard].
se ti riferisci all'ultimo punto l'aveva consigliato Fabio ma gli abbiamo detto chiaramente che pensavamo di farlo dopo l'RTB per il progetto vero e proprio; lo terrei comunque perchè di fatto è stato accennato ma se dici levo.

2024-01-11 13:21 UTC, closed without merging