160 issueona adr
SWATEngineering/Docs pull request #188
Opened 2024-01-13 09:07 UTC by RiccardoTonioloDev

2024-01-14 22:30 UTC, Dovid308 commented on src/2_RTB/AnalisiDeiRequisiti/content.typ
> +- *Postcondizioni*: l'amministratore pubblico visualizza dei #glossary("pannelli") contenenti dati relativi al vento.
domandona: qui perchè è stato reso più ambiguo di prima?

so che per la media mobile ne stai discutendo con matteo, nel caso fammi sapere anche a me

2024-01-14 22:53 UTC, Dovid308 commented on src/2_RTB/AnalisiDeiRequisiti/content.typ
> +=== UC2.4.2: Visualizzazione tabella velocità del vento
qui perchè hai deciso di andare a creare un sottocaso d'uso e non un altro caso d'uso? 

credo siamo nel caso della descrizione, ma perchè per esempio per la temperatura e l'inquinamento non è stato fatto nella stessa modalità?

2024-01-14 22:59 UTC, Dovid308 commented on src/2_RTB/AnalisiDeiRequisiti/content.typ
> +
mi puoi ricordare perchè esiste questo caso d'uso? mi sembra molto simile al 2 

stessa cosa per 3 e 3.1 

dovvaro non mi ricordo e non vedo la differenza :(

2024-01-14 23:08 UTC, Dovid308 commented on src/2_RTB/AnalisiDeiRequisiti/content.typ
> +- *Postcondizioni*: l'amministratore pubblico visualizza un #glossary("pannello") contenente una mappa indicante lo stato di congestione delle strade, mediante gli stati "LOW", "MEDIUM", "HIGH" e "BL
qui secondo me rimane ancora poco chiaro, tralaltro forse ridondante.

2024-01-14 23:13 UTC, Dovid308 commented on src/2_RTB/AnalisiDeiRequisiti/content.typ
> +  + l'amministratore pubblico seleziona la visualizzazione della deshboard delle anomalie.
quel deshboard?

2024-01-14 23:14 UTC, Dovid308 commented on src/2_RTB/AnalisiDeiRequisiti/content.typ
> +  + l'amministratore pubblico seleziona la visualizzazione della deshboard delle anomalie.
comunque qui c'è da aggiornare la postcondizione

2024-01-14 23:22 UTC, Dovid308 commented on src/2_RTB/AnalisiDeiRequisiti/content.typ
>  === UC5: Visualizzazione allerte superamento soglie
Non viene detto niente sul formato di questa allerta, forse sarebbe da farci un caso d'uso apposta.

2024-01-15 20:54 UTC, Dovid308 commented on src/2_RTB/AnalisiDeiRequisiti/content.typ
> +- *Postcondizioni*: l'amministratore pubblico visualizza i dati ordinati nella tabella, secondo tale campo.
il "tale campo" viene citato all'interno delle post condizioni ma non ha un corrispondente nella precondizione

2024-01-15 21:00 UTC, Dovid308 commented on src/2_RTB/AnalisiDeiRequisiti/content.typ
> +  + il sensore formatta il messaggio da inviare al sistema, di modo da mandare la temperatura, espressa in gradi Celsius, il timestamp di rilevazione e le proprie coordinate;
punto serio, siamo sicuri di voler mandare i dati sulle cordinate geografiche come relativi alla rilvazione e no invece come dati propri del sensore?

2024-01-15 21:21 UTC, Dovid308 commented on src/2_RTB/AnalisiDeiRequisiti/content.typ
> +  + il sensore formatta il messaggio da inviare al sistema, di modo da mandare il timestamp di rilevazione e le coordinate della bicicletta;
qui non c'è il riferimento alla percetuale di batteria.

2024-01-15 21:57 UTC, Dovid308 commented on src/2_RTB/AnalisiDeiRequisiti/content.typ
> +     "Obbligatorio", "L'utente deve poter visualizzare un menù di selezione delle dashboard, che permetta di selezionare tra Sensori, Ambientale, Urbanistica e Dati anomali & superamento soglie.", [U
perchè qui è messo dappertutto l'utente? e non amministratore pubblico?

2024-01-16 15:20 UTC, ranghetto requested changes
Vanno modificati tutti i punti in cui si parla di media mobile, perche' in realta' e' una media matematica di raggruppamento su periodo di 5 minuti. La media mobile secondo me si puo' fare giusto su un paio di tipi di dati giusto per mostrarla, magari su: temperatura e precipitazioni ad esempio.

2024-01-16 15:20 UTC, ranghetto commented on src/2_RTB/AnalisiDeiRequisiti/content.typ
> +=== UC2.4.2: Visualizzazione tabella velocità del vento
Anche secondo me qui non e' necessaria la specializzazione ma possono rimanere separati

2024-01-16 15:20 UTC, ranghetto commented on src/2_RTB/AnalisiDeiRequisiti/content.typ
> +  + l'amministratore pubblico seleziona la visualizzazione della deshboard delle anomalie.
Perche' da aggiornare? Scrivi anche il motivo per cui secondo te non va bene altrimenti sos si capisce il perche' dei tuoi commenti

2024-01-16 18:05 UTC, RiccardoTonioloDev commented on src/2_RTB/AnalisiDeiRequisiti/content.typ
> +=== UC2.4.2: Visualizzazione tabella velocità del vento
- [ ] TODO: rimuovere specializzazione, e tenerli separati

2024-01-16 18:06 UTC, RiccardoTonioloDev commented on src/2_RTB/AnalisiDeiRequisiti/content.typ
> +  + l'amministratore pubblico seleziona la visualizzazione della deshboard delle anomalie.
- [ ] TODO: mettere dashboard come glossariato.

2024-01-16 18:07 UTC, RiccardoTonioloDev commented on src/2_RTB/AnalisiDeiRequisiti/content.typ
> +- *Postcondizioni*: l'amministratore pubblico visualizza i dati ordinati nella tabella, secondo tale campo.
- [ ] TODO: migliorare chiarezza espostiva "ordinamento per campi della tabella"

2024-01-16 18:09 UTC, RiccardoTonioloDev commented on src/2_RTB/AnalisiDeiRequisiti/content.typ
> +  + il sensore formatta il messaggio da inviare al sistema, di modo da mandare la temperatura, espressa in gradi Celsius, il timestamp di rilevazione e le proprie coordinate;
Si, meglio di si perchè sennò dovremmo prendere solo alcuni dati del sensore dal json e metterli comunque nella tabella delle temperature, e penso sia uno spono per fare il collegamento diretto Kafka -> ClickHouse. Chiedo conferma a @ranghetto

2024-01-16 18:10 UTC, RiccardoTonioloDev commented on src/2_RTB/AnalisiDeiRequisiti/content.typ
> +     "Obbligatorio", "L'utente deve poter visualizzare un menù di selezione delle dashboard, che permetta di selezionare tra Sensori, Ambientale, Urbanistica e Dati anomali & superamento soglie.", [U
@ranghetto tu che dici? Vedo che l'hai marchiata come resolved, me non è più corretto come dice @Dovid308 ?

2024-01-17 11:17 UTC, RiccardoTonioloDev commented
> Non c'e' piu' quindi un UC o un requisito per la media mobile della temperatura?

Esattamente, al massimo aggiungiamo qualche vincolo in opzionale dopo l'RTB

2024-01-17 13:13 UTC, ranghetto requested changes
lgtm

2024-01-17 13:14 UTC, ranghetto approved these changes
lgtm

2024-01-17 13:20 UTC, RiccardoTonioloDev commented on src/2_RTB/AnalisiDeiRequisiti/changelog.csv
> +0.13,13-01-2024,"Correzione use case, aggiunta o modifica immagini, disambiguazione e aggiunta dei requisiti.", Riccardo Toniolo, Analista
Si va bene, ma per favore la prossima volta usa i `suggestion` per robe del genere.

2024-01-17 13:22 UTC, ranghetto approved these changes
yup

2024-01-17 13:22 UTC, merged