185 verbale interno 11/01/24
SWATEngineering/Docs pull request #190
Opened 2024-01-17 13:49 UTC by nance97

2024-01-17 22:09 UTC, lonewalker0 requested changes

2024-01-17 22:09 UTC, lonewalker0 commented on src/2_RTB/VerbaliInterni/VerbaleInterno_110124/content.typ
> +Il team ha successivamente discusso di come sia più appropriato riportare ed evidenziare gli effetti del nuovo budget preventivato (nuovo BAC o "Budget At Completion") all'interno del _Piano di Quali
```suggestion
Il team ha successivamente discusso di come sia più appropriato riportare ed evidenziare gli effetti del nuovo budget preventivato (nuovo BAC o "Budget At Completion") all'interno del _Piano di Qualifica v1.0_. Durante la discussione sono state esplorate due alternative principali: applicare il nuovo BAC solo agli #glossary[sprint] successivi alla revisione #glossary[RTB], oppure iniziare ad applicarlo dal #glossary[sprint] 7 (il quale coincide con la creazione del nuovo preventivo) in avanti. Il team ha scelto la seconda alternativa, con l'intenzione di evidenziare l'adattamento del team all'andamento del progetto fino al settimo #glossary[sprint]. In questo modo, si intende valutare se i valori accettabili stabiliti inizialmente per le metriche misurate fino a quel momento siano adeguati rispetto al nuovo BAC.
```

2024-01-17 22:09 UTC, lonewalker0 commented on src/2_RTB/VerbaliInterni/VerbaleInterno_110124/content.typ
> +- Le ore dedicate al ruolo di Verificatore sono diminuite nel nuovo preventivo (ne erano previste 162 inizialmente, ora 137), il team ne ha utilizzate 65 nel corso dei primi otto #glossary[sprint]. L
```suggestion
- Le ore dedicate al ruolo di Verificatore sono diminuite nel nuovo preventivo (ne erano previste 162 inizialmente, ora 137), il team ne ha utilizzate 65 nel corso dei primi otto #glossary[sprint]. Le ore da Verificatore aumentano però rispetto a quelle da Programmatore in confronto al vecchio preventivo, in quanto ci si è resi conto che si tratta del ruolo che ha consumato il maggior numero di ore produttive in generale fino ad oggi e le responsabilità dei Verificatori non faranno che aumentare dopo la revisione #glossary[RTB]. Oltre alla revisione di documentazione e codice, saranno responsabili anche dello sviluppo di tutti i test per assicurare che il prodotto software soddisfi i requisiti di qualità che verranno specificati sempre più in dettaglio all'interno del _Piano di Qualifica_.
```

2024-01-17 22:11 UTC, lonewalker0 commented
segna questi termini come mancanti grafana, ca, rtb, pb

2024-01-18 16:34 UTC, nance97 commented
> segna questi termini come mancanti grafana, ca, rtb, pb

sì perchè sono termini che ho inserito nel glossario all'interno della issueona del PdP.

2024-01-20 12:49 UTC, merged