Stestura verbale intarno 15-02-24
SWATEngineering/Docs pull request #227
Opened 2024-02-18 10:39 UTC by ranghetto

2024-02-19 13:19 UTC, nance97 requested changes

2024-02-19 13:19 UTC, nance97 commented on src/3_PB/VerbaliInterni/VerbaleInterno_240215/content.typ
> +indicazioni dateci dal professor Cardin duranete la revisione RTB.
```suggestion
indicazioni dateci dal professor Cardin durante la revisione RTB.
```

2024-02-19 13:19 UTC, nance97 commented on src/3_PB/VerbaliInterni/VerbaleInterno_240215/content.typ
> +consuntivi di periodo e come incorporarle in questi ultime. In merito a questo è stato deciso di
```suggestion
consuntivi di periodo e come incorporarle in questi ultimi. In merito a questo è stato deciso di
```

2024-02-19 13:19 UTC, nance97 commented on src/3_PB/VerbaliInterni/VerbaleInterno_240215/content.typ
> +per calcolare le tabelle del consuntivo.
```suggestion
- Calcolare le metriche relative allo sprint concluso e aggiornare i grafici del _Piano di Qualifica_;
- Assicurarsi che tutti abbiano immesso le loro ore produttive nel documento interno "Time & Resource Manager" per calcolare le tabelle del consuntivo.
```

2024-02-19 13:19 UTC, nance97 commented on src/3_PB/VerbaliInterni/VerbaleInterno_240215/content.typ
> +Riccardo Costantin è incaricato di sistemare il documento "Analisi dei Requisiti" secondo le
```suggestion
Riccardo Costantin è incaricato di sistemare il documento _Analisi dei Requisiti_ secondo le
```

2024-02-19 13:19 UTC, nance97 commented on src/3_PB/VerbaliInterni/VerbaleInterno_240215/content.typ
> +- "pipes & filters".
```suggestion
In seguito, si è deciso di studiare il contenuto da inserire nel documento _Specifiche Tecniche_, in particolare:
- Architetture layered (a strati) ed event-driven;
- "Pipes & filters".
```

2024-02-19 13:19 UTC, nance97 commented on src/3_PB/VerbaliInterni/VerbaleInterno_240215/meta.typ
> +#let fine_incontro = "16:30"
```suggestion
#let fine_incontro = "15:30"
```

2024-02-21 17:19 UTC, simocare commented
- [ ] Va aggiunta la colonna per il verificatore.

2024-02-24 12:27 UTC, nance97 requested changes

2024-02-24 12:27 UTC, nance97 commented on src/3_PB/VerbaliInterni/VerbaleInterno_240215/content.typ
> +- "Pipes & filters"..
```suggestion
- "Pipes & filters".
```

2024-02-24 12:27 UTC, nance97 commented on src/3_PB/VerbaliInterni/VerbaleInterno_240215/changelog.csv
> +0.1,19-02-2024,Prima stesura,Matteo Rango,Responsabile
volendo aggiungere la colonna per il verificatore come fatto altrove:

in changelog.typ
#let changelog = csv("changelog.csv")
#table(
  columns: (1fr, 2fr, 4fr, 2fr, 2fr, 2fr),
  [*Versione*], [*Data*], [*Descrizione*], [*Autore*], [*Ruolo*], [*Verificatore*],
  ..changelog.rev().flatten()
)

2024-02-24 12:27 UTC, nance97 commented on src/3_PB/VerbaliInterni/VerbaleInterno_240215/changelog.csv
> +0.1,19-02-2024,Prima stesura,Matteo Rango,Responsabile
```suggestion
0.1,19-02-2024,Prima stesura,Matteo Rango,Responsabile,Nancy Kalaj
```

2024-02-24 14:54 UTC, nance97 approved these changes

2024-02-24 14:54 UTC, merged