228 ndp aggiunte e fix
SWATEngineering/Docs pull request #230
Opened 2024-02-21 12:00 UTC by lonewalker0

2024-02-22 09:23 UTC, lonewalker0 commented
- [ ]  aggiornare il changelog

2024-02-22 14:08 UTC, nance97 requested changes
intanto questi, mi mancano alcune cose alla fine ma ci arrivo dopo

2024-02-22 14:08 UTC, nance97 commented on src/3_PB/NormeDiProgetto/content.typ
> +È presente il file `meta.typ` per indicare le variabili di inizio, fine incontro e luogo in cui si è svolto, basta andare a modificarle e automaticamente vengono riportate nel documento.
```suggestion
Per indicare i partecipanti presenti all'incontro si utilizza un file csv, dove in ogni riga si ha il partecipante e la durata della sua presenza separati da virgola; questo file viene poi convertito automaticamente in una tabella da un'apposita funzione #glossary[Typst]. 
Si utilizza inoltre il file `meta.typ` per indicare l'ora di inizio e fine incontro e luogo in cui si è svolto, è sufficiente modificarlo con i dati opportuni in modo che vengano automaticamente riportati nel documento.
```

2024-02-22 14:08 UTC, nance97 commented on src/3_PB/NormeDiProgetto/content.typ
> +                - Per indicare parti di codice in #glossary[Typst] o in altri linguaggio.
```suggestion
                - Per indicare parti di codice in #glossary[Typst] o in altri linguaggi.
```

2024-02-22 14:08 UTC, nance97 commented on src/3_PB/NormeDiProgetto/content.typ
> +        - *Proof of Concepts* → *PoC*.
```suggestion
        - *Proof of Concept* → *PoC*.
```

2024-02-22 14:08 UTC, nance97 commented on src/3_PB/NormeDiProgetto/content.typ
> +        - Partecipare attivamente agli argomenti dell’ordine del giorno;
```suggestion
        - Partecipare attivamente agli argomenti dell’#glossary[ordine del giorno];
```

2024-02-22 14:08 UTC, nance97 commented on src/3_PB/NormeDiProgetto/content.typ
> +All'interno della cartella `src`, sono presenti 2 cartelle, contenenti altre sotto-cartelle, organizzate in questo modo (non sono presenti i file `.pdf` poiché l'automazione di Github Action si occup
```suggestion
All'interno della cartella `src`, sono presenti 2 cartelle organizzate nel modo seguente (non sono presenti i file compilati in formato `.pdf` poiché un'automazione Github Action si occupa di effettuare la compilazione automatica dei documenti e renderli disponibili all'interno di un artefatto):
```

2024-02-22 14:08 UTC, nance97 commented on src/3_PB/NormeDiProgetto/content.typ
> +        - `git clone URL_repo`: per clonare il repository git remoto in locale. Si preferisce la clonazione tramite SSH;
```suggestion
        - `git clone URL_repo`: per clonare il #glossary[repository] git remoto in locale. Si preferisce la clonazione tramite SSH;
```

2024-02-22 14:32 UTC, lonewalker0 commented on src/3_PB/NormeDiProgetto/content.typ
> +La definizione dell'architettura del prodotto è affidata ai Progettisti. Questa serve da base per lo sviluppo del software e deve garantire che le varie componenti siano facilmente identificabili, co
la tolgo è troppo slegata

2024-02-22 14:38 UTC, lonewalker0 commented on src/3_PB/NormeDiProgetto/content.typ
> +È presente il file `meta.typ` per indicare le variabili di inizio, fine incontro e luogo in cui si è svolto, basta andare a modificarle e automaticamente vengono riportate nel documento.
eh già, rendere le norme più procedurali, con all'interno i tutorial passo passo così vediamo se gli va bene

2024-02-22 14:57 UTC, lonewalker0 commented on src/3_PB/NormeDiProgetto/content.typ
> +        - Tracciamento dei requisiti: l'attività di progettazione deve essere coerente con quanto descritto all'interno dell'_Analisi dei requisiti v2.0_;
la prima l'avevo intesa in senso generale, la seconda proprio la costruzione della tabella mettendo codice del requisito, descrizione e soddisfatto/non soddisfatto, non servirebbe anche la fonte

2024-02-23 09:23 UTC, nance97 requested changes

2024-02-23 09:23 UTC, nance97 commented on src/3_PB/NormeDiProgetto/content.typ
> +        - `git add .`: per aggiungere tutti i file modificati nell'area di staging, in caso non si vuole aggiungerli tutti specificare il nome del file; assicurarsi di essere nella cartella corretta;
```suggestion
        - `git add .`: per aggiungere tutti i file modificati all'area di staging; in caso non si voglia aggiungerli tutti, occorre specificare il nome di ciascun file da aggiungere singolarmente, assicurandosi anche di essere nella cartella corretta;
```

2024-02-23 09:23 UTC, nance97 commented on src/3_PB/NormeDiProgetto/content.typ
> +        - `git commit -m "nome_messaggio"`: per registrare i cambiamenti effettuati; sono delle istantanee dello stato di progetto in un dato momento; `-m` specifica il messaggio del commit, e possib
```suggestion
        - `git commit -m "nome_messaggio"`: per registrare i cambiamenti apportati ad un determinato prodotto, documentale o software; i commit possono essere visti come istantanee dello stato di un prodotto in un dato momento. `-m` specifica il messaggio del commit, e deve essere una descrizione breve ma quanto più dettagliata dei cambiamenti apportati;
```

2024-02-23 09:23 UTC, nance97 commented on src/3_PB/NormeDiProgetto/content.typ
> +        - `git push`: le modifiche locali registrate vengono inviati al branch remoto;
```suggestion
        - `git push`: le modifiche locali registrate vengono inviate al branch remoto;
```

2024-02-23 09:23 UTC, nance97 commented on src/3_PB/NormeDiProgetto/content.typ
> +        - `git pull`: per scaricare le modifiche remote all'interno del repo locale;
```suggestion
        - `git pull`: per importare le modifiche effettuate su un branch remoto all'interno del branch locale corrispondente;
```

2024-02-23 09:23 UTC, nance97 commented on src/3_PB/NormeDiProgetto/content.typ
> +        - `git pull --rebase origin nome_branch`: in caso più persone stanno lavorando allo stesso branch e si verificano conflict merge al momento del `git pull`, fa il rebase del branch corrente pe
```suggestion
        - `git pull --rebase origin nome_branch`: in caso più persone stiano lavorando allo stesso branch e si verifichino conflict merge al momento del `git pull`, fa il rebase del branch locale corrente per ottenere la linea cronologica dei vari commit eseguiti e aggiornarlo rispetto alla #glossary[repository] remota;
```

2024-02-23 09:23 UTC, nance97 commented on src/3_PB/NormeDiProgetto/content.typ
> +        - `git rebase origin/main`: per fare il rebase in caso il main ricevesse aggiornamenti importanti e il nostro branch non è aggiornato;
```suggestion
        - `git rebase origin/main`: per fare il rebase in caso il main riceva aggiornamenti importanti, in modo che vengano importati all'interno del branch di lavoro corrente;
```

2024-02-23 09:23 UTC, nance97 commented on src/3_PB/NormeDiProgetto/content.typ
> +Il processo di validazione consiste nella conferma che il software sviluppato sia conforme ai requisiti e alle aspettative della Proponente.
```suggestion
Il processo di validazione è un processo di supporto il cui obiettivo primario è ottenere la conferma che il software sviluppato rispetti le aspettative della Proponente.
```

2024-02-23 09:23 UTC, nance97 commented on src/3_PB/NormeDiProgetto/content.typ
> +Lo scopo principale della validazione è garantire che il software sia correttamente implementato e funzioni correttamente nel contesto operativo previsto, fornendo un prodotto finale soddisfacente e
```suggestion
Lo scopo principale della validazione è quindi garantire che il software sia implementato in maniera adeguata e che funzioni correttamente nel contesto operativo previsto, fornendo un prodotto finale soddisfacente e conforme alle esigenze della Proponente.
```

2024-02-23 09:23 UTC, nance97 commented on src/3_PB/NormeDiProgetto/content.typ
> +Prima di richiedere il test, i Verificatori si preoccupano di eseguire i test di sistema in un ambiente identico a quello di installazione: è precondizione necessaria del collaudo che i test di siste
```suggestion
Prima di effettuare i test di accettazione, i Verificatori hanno la responsabilità di eseguire i test di sistema in un ambiente identico a quello di installazione: è precondizione necessaria del collaudo che i test di sistema diano esito positivo.
```

2024-02-23 16:06 UTC, nance97 approved these changes

2024-02-23 16:08 UTC, merged