236 Update NdP con ST
SWATEngineering/Docs pull request #243
Opened 2024-02-24 14:48 UTC by nance97

2024-02-24 17:06 UTC, Dovid308 requested changes
review effettuata, ti prego di dare un occhiata in generale a tutta la parte sulla progettazione, non vedo come RTB possa essere una sottoattvità del processo di progettazione.

2024-02-24 17:06 UTC, Dovid308 commented on src/3_PB/NormeDiProgetto/content.typ
> +        - *#glossary[Architettura]*: presenta i componenti architetturali del #glossary[sistema], descrivendo i #glossary[design pattern] e le #glossary[best practices] utilizzate per organizzare e i
diagrammi di deployment non verranno utilizzati credo, eviterei di entrarre nello specifico di quali tipologie.

2024-02-24 21:29 UTC, nance97 commented on src/3_PB/NormeDiProgetto/content.typ
> +
è stato così sin dal primo sprint sì
@simocare cosa ne pensi? l'ho inserito perchè ho visto che hai creato una issue a tal proposito stamattina

2024-02-25 16:06 UTC, Dovid308 commented on src/3_PB/NormeDiProgetto/content.typ
> +
io comunque rimuoverei la parte relativa all'eccezione dei primi due sprint dato che qui non ha valore l'informazione. @nance97 


Le parole del Prof. Oak rimbombano: "C'è un luogo e un momento per ogni cosa! Ma non ora."

2024-02-26 14:12 UTC, simocare commented on src/3_PB/NormeDiProgetto/content.typ
> +
Serve quella parte ma sono d'accordo con @Dovid308 sul fatto di togliere il discorso sui primi due sprint. Sulle NdP teniamo le norme da seguire ad OGGI, quindi non ci interessa quello che abbiamo fatto all'inizio.

2024-03-05 07:52 UTC, Dovid308 requested changes

2024-03-05 07:52 UTC, Dovid308 commented on src/3_PB/NormeDiProgetto/content.typ
io questa parte le rimuoverei, non saprei neanche se è  teoricamente corretta

2024-03-05 07:54 UTC, Dovid308 commented on src/3_PB/NormeDiProgetto/content.typ
forse non ho selezionato bene, la parte che intendo è tutta quella relativa alle 3 sottoattività

2024-03-07 14:46 UTC, Dovid308 approved these changes

2024-03-07 14:46 UTC, merged