verbale esterno 13/03
SWATEngineering/Docs pull request #274
Opened 2024-03-14 17:55 UTC by Dovid308

ho anche modificato l'adr il changelog che mancavano i verificatori dell'ultima versione

2024-03-15 15:30 UTC, lonewalker0 submitted a review, later dismissed

2024-03-15 21:58 UTC, Dovid308 commented on src/3_PB/VerbaliEsterni/VerbaleEsterno_240313/content.typ
> +Un membro del gruppo ha domandato se utilizzare il software Selenium per testare l'effettivo funzionamento della pipeline fino a Grafana fosse adeguato. La risposta è stata negativa.
mi piace di più così come è

2024-03-15 21:59 UTC, Dovid308 commented on src/3_PB/VerbaliEsterni/VerbaleEsterno_240313/content.typ
> +== Pianificazione SAL
io ce l'ho la frase, mah

2024-03-16 17:26 UTC, nance97 requested changes

2024-03-16 17:26 UTC, nance97 commented on src/3_PB/VerbaliEsterni/VerbaleEsterno_240313/content.typ
> +L'incontro si è aperto con la presentazione dell'attuale componente di visualizzazione e con una breve discussione riguardo ai progressi effettuati dall'ultimo SAL. Successivamente si è discussa la p
```suggestion
L'incontro si è aperto con la presentazione dello stato attuale della componente di visualizzazione del prodotto software (Grafana) e con una breve discussione riguardo ai progressi effettuati dall'ultimo SAL, ovvero la ridefinizione dell'architettura sottostante e l'aggiunta di molteplici simulatori. Successivamente, si è discussa la pianificazione temporale dell'attività di codifica per i prossimi sprint.
```

2024-03-16 17:26 UTC, nance97 commented on src/3_PB/VerbaliEsterni/VerbaleEsterno_240313/content.typ
> +Il team ha messo al corrente la Proponente della recente decisione intrapresa di non affrontare la revisione CA e dunque di volersi limitare alla revisione PB pianificata orientativamente la prima se
```suggestion
Il team ha messo al corrente la Proponente della decisione intrapresa di recente di non affrontare la revisione CA e dunque di volersi limitare alla revisione PB, pianificata orientativamente verso la prima settimana di Aprile. 
```

2024-03-16 17:26 UTC, nance97 commented on src/3_PB/VerbaliEsterni/VerbaleEsterno_240313/content.typ
> +Il team ha domandato alla Proponente riguardo quali sarebbero state le modalità preferibili per testare l'integrazione dei componenti.
```suggestion
Il team ha domandato alla Proponente quali potrebbero essere le modalità preferibili per testare l'integrazione dei componenti del prodotto software.
```
più che le modalità preferibili direi gli strumenti più adatti ma it's up to you

2024-03-16 17:26 UTC, nance97 commented on src/3_PB/VerbaliEsterni/VerbaleEsterno_240313/content.typ
> +Un membro del gruppo ha domandato se utilizzare il software Selenium per testare l'effettivo funzionamento della pipeline fino a Grafana fosse adeguato. La risposta è stata negativa.
```suggestion
In particolare, un membro del gruppo ha domandato se utilizzare il software Selenium per testare l'effettivo funzionamento della pipeline fino a Grafana fosse adeguato. In risposta, la Proponente ne ha sconsigliato l'utilizzo onde evitare un ulteriore dispendio di risorse e una maggiore complessità.
```

2024-03-16 17:26 UTC, nance97 commented on src/3_PB/VerbaliEsterni/VerbaleEsterno_240313/content.typ
> +In quanto le statistiche offerte direttamente da Docker potrebbero essere influenzate dalle specifiche tecniche della macchina utilizzata, il team ha domandato alla Proponente riguardo quali sarebber
```suggestion
In quanto le statistiche offerte direttamente da Docker potrebbero essere influenzate dalle specifiche tecniche della macchina utilizzata, il team ha domandato alla Proponente quali sarebbero le migliori tecnologie per poter testare le performance del prodotto.
```

2024-03-16 17:26 UTC, nance97 commented on src/3_PB/VerbaliEsterni/VerbaleEsterno_240313/content.typ
> +Viene consigliato di verificare se la tecnologia "Portainer" possa essere utile allo scopo. Inoltre viene consigliato di contattare il rappresentante aziendale Andrea Dorigo tramite mail per avere un
```suggestion
Viene consigliato di verificare se la tecnologia "Portainer" possa essere utile allo scopo. Inoltre, viene consigliato di contattare il rappresentante aziendale Andrea Dorigo tramite email per ricevere ulteriori consigli in merito.
```

2024-03-16 17:26 UTC, nance97 commented on src/3_PB/VerbaliEsterni/VerbaleEsterno_240313/content.typ
> +Viene sollevato l'interrogativo riguardo alle modalità di attestazione del prodotto come minimum viable product (MVP), e se la procedura sia rimasta la medesima rispetto all'anno accademico 2022/2023
```suggestion
La Proponente ha sollevato un interrogativo riguardo alle modalità di attestazione del prodotto come Minimum Viable Product (MVP), e se la procedura sia rimasta la medesima rispetto all'anno accademico 2022/2023. Il team non ne è al momento a conoscenza, provvederà ad informarsene durante il diario di bordo programmato per venerdì 15 Marzo e riporterà tale informazione alla Proponente quanto prima.
```

2024-03-16 17:26 UTC, nance97 commented on src/3_PB/VerbaliEsterni/VerbaleEsterno_240313/content.typ
> +Viene pianificato il prossimo SAL in data mercoledì 20 Marzo alle ore 16.30. Il team presenta la sua volontà di mantenere un contatto più stretto data la fase conclusiva in corso, al fine di assicura
```suggestion
Infine, si è deciso di fissare il prossimo SAL in data mercoledì 20 Marzo alle ore 16.30. Questo in quanto il team ha rimarcato la volontà di mantenere un contatto più stretto con la Proponente, accingendosi ad entrare nel periodo conclusivo del progetto. In tale periodo è infatti molto importante perseguire una risoluzione tempestiva di eventuali problemi che potrebbero emergere e, di conseguenza, portare a ritardi rispetto alla pianificazione. 
```

2024-03-17 12:31 UTC, nance97 reviewed
da rimuovere Andrea dalla lista dei partecipanti, a parte quello okay

2024-03-19 20:55 UTC, Dovid308 commented
@nance97 okay ho rimosso dai partecipanti andrea, se vuoi approva e mergia direttamente

2024-03-20 08:36 UTC, nance97 approved these changes

2024-03-20 08:37 UTC, merged