consuntivo 12
SWATEngineering/Docs pull request #280
Opened 2024-03-15 17:29 UTC by lonewalker0

2024-03-15 22:24 UTC, Dovid308 requested changes

2024-03-15 22:24 UTC, Dovid308 commented on src/3_PB/PianoDiProgetto/sections/ConsuntivoSprint/DodicesimoSprint.typ
> +L'unico rischio emerso durante lo #glossary[sprint] corrente è legato al rischio RT1 - Conoscenze tecnologiche limitate, infatti il team ha avuto particolari problemi a definire come effettuare la fa
qui potresti cucinare meglio secondo me, tralatro bro "l'assenza della persona esperta ..." è bruttino da mettere

2024-03-15 22:24 UTC, Dovid308 commented on src/3_PB/PianoDiProgetto/sections/ConsuntivoSprint/DodicesimoSprint.typ
> +Per quanto riguarda le ore impiegate dal Verificatore, sono state inferiori a quanto preventivato a causa della scarsa completezza dei contenuti documentativi forniti in questo #glossary[sprint].
scarsa completezza non mi piace molto

2024-03-15 22:24 UTC, Dovid308 commented on src/3_PB/PianoDiProgetto/sections/ConsuntivoSprint/DodicesimoSprint.typ
> +È stata anche avviata la stesura del documento _Manuale Utente_.
questa va tolta

2024-03-17 10:17 UTC, Dovid308 commented on src/3_PB/PianoDiProgetto/sections/PianificazioneSprint/TredicesimoSprint.typ
> +- #glossary[Dashboard] per filtraggio e allerte in #glossary[Grafana];
questa non vuol dire niente. dashboard per filtraggio?

2024-03-17 11:45 UTC, nance97 requested changes

2024-03-17 11:45 UTC, nance97 commented on src/3_PB/PianoDiProgetto/sections/ConsuntivoSprint/DodicesimoSprint.typ
> +Nella retrospettiva è stato evidenziato il rispetto del totale delle ore preventivate per questo sprint, con una differenza minima di soli trenta minuti tra il preventivo e il consuntivo, costituendo
```suggestion
Nella retrospettiva è stato evidenziato il rispetto del totale delle ore preventivate per questo #glossary[sprint] con una differenza di soli 30 minuti tra il preventivo e il consuntivo, il che costituisce un tasso di errore dell'1% circa (0.86%). È notevole come il team sia riuscito a gestire senza particolari intoppi un regime sostenuto di circa 60 ore produttive settimanali, dimostrando così impegno e coerenza nel rispettare le scadenze prefissate per arrivare il prima possibile alla seconda revisione #glossary[PB].
```

2024-03-17 11:45 UTC, nance97 commented on src/3_PB/PianoDiProgetto/sections/ConsuntivoSprint/DodicesimoSprint.typ
> +Nel consuntivo emerge che sono state consumate più ore da Amministratore rispetto a quanto preventivato, principalmente a causa della necessità di creare alcuni script per automatizzare l'ambiente di
ti riferisici a quelli per il calcolo delle metriche di prodotto vero? se sì, lo espliciterei

2024-03-17 11:45 UTC, nance97 commented on src/3_PB/PianoDiProgetto/sections/ConsuntivoSprint/DodicesimoSprint.typ
> +Per quanto riguarda l'attività di codifica, possiamo affermare che con l'ultima implementazione dei sensori urbanistici rimanenti, la parte relativa alla simulazione potrebbe essere considerata concl
```suggestion
Per quanto riguarda l'attività di codifica, si può affermare che, con l'ultima implementazione dei sensori urbanistici rimanenti, la parte del prodotto software relativa alla simulazione dei dati potrebbe essere considerata conclusa. Questo traguardo è stato raggiunto in breve tempo grazie ad una buona distribuzione del lavoro a carico dei Programmatori; infatti, ciascun membro del team si è dedicato allo sviluppo di uno o due sensori diversi nel corso degli ultimi due #glossary[sprint] e, in tal modo, il team è riuscito a realizzare gli 11 sensori previsti dall'_Analisi dei Requisiti_ e a coniugarli con la nuova #glossary[architettura].
```

2024-03-17 11:45 UTC, nance97 commented on src/3_PB/PianoDiProgetto/sections/ConsuntivoSprint/DodicesimoSprint.typ
> +Per quanto riguarda le ore impiegate dal Verificatore, sono state inferiori a quanto preventivato a causa della ridotta quantità dei contenuti documentativi forniti in questo #glossary[sprint], il te
```suggestion
Per quanto riguarda le ore impiegate dai Verificatori, queste sono state inferiori a quanto preventivato poiché il team si è concentrato prevalentemente sull'attività di codifica, dedicando relativamente meno tempo alla #glossary[documentazione]; infatti, il team ha ritenuto opportuno attendere che il prodotto software fosse sviluppato quasi nella sua interezza per applicare eventuali modifiche migliorative alle _Specifiche Tecniche_ e proseguire con la stesura del _Manuale Utente_.
```

2024-03-17 11:45 UTC, nance97 commented on src/3_PB/PianoDiProgetto/sections/ConsuntivoSprint/DodicesimoSprint.typ
> +Durante lo #glossary[sprint] attuale, l'unico rischio che si è evidenziato è stato il rischio RT1 - Conoscenze tecnologiche limitate. Il team ha incontrato delle difficoltà particolari nel definire i
```suggestion
Durante lo #glossary[sprint] attuale, l'unico rischio che si è manifestato è stato il rischio RT1 - Conoscenze tecnologiche limitate. Il team ha incontrato delle difficoltà nel definire il metodo ottimale per condurre i test del prodotto e selezionare i software pertinenti. Nonostante il rischio sia stato parzialmente mitigato attraverso un incontro con la Proponente, dove si è discusso anche delle strategie da attuare per la parte di testing, non tutte le domande hanno ricevuto una risposta esaustiva e ciò ha contribuito a rallentare il processo decisionale. I componenti del team tenteranno di implementare i primi test di unità e di integrazione con le conoscenze attualmente in loro possesso e chiederanno un altro riscontro da parte della Proponente nell'arco di una settimana.
```

2024-03-19 13:41 UTC, nance97 requested changes
da risolvere le conversazioni aperte in precedenza

2024-03-20 08:52 UTC, Dovid308 commented
@lonewalker0 ma perchè hai cambiato cruscotto delle metriche e cruscotto della qualità anche in maniera retroattiva? 


Inoltre hai cambiato il preventivo per il 13 sprint, ma non credo tu abbia aggiornato i grafici che sono ancora quelli vecchi

2024-03-22 12:41 UTC, Dovid308 approved these changes

2024-03-23 13:42 UTC, nance97 approved these changes

2024-03-23 13:43 UTC, merged