verbale
SWATEngineering/Docs pull request #286
Opened 2024-03-20 18:33 UTC by lonewalker0

2024-03-20 22:05 UTC, Dovid308 commented on src/3_PB/VerbaliEsterni/VerbaleEsterno_240320/content.typ
> +Considerando l'avvio del secondo lotto per il progetto didattico, la Proponente ha sollevato la necessità di rispettare gli impegni presi per garantire il completamento tempestivo. Ciò consentirebbe
è uno solo il gruppo mi sembra sai

2024-03-20 22:16 UTC, lonewalker0 commented on src/3_PB/VerbaliEsterni/VerbaleEsterno_240320/content.typ
> +Considerando l'avvio del secondo lotto per il progetto didattico, la Proponente ha sollevato la necessità di rispettare gli impegni presi per garantire il completamento tempestivo. Ciò consentirebbe
2 da tabellone

2024-03-20 22:19 UTC, Dovid308 commented on src/3_PB/VerbaliEsterni/VerbaleEsterno_240320/content.typ
> +È stato concordato di programmare il prossimo SAL per martedì 02/04/2024, con l'orario ancora da definire, direttamente presso la sede della Proponente. L'incontro vedrà la partecipazione di Andrea D
non è stato concordato, hanno detto che dobbiamo fargli sapere noi, io per allungare il brodo lo scriverei.

2024-03-20 22:19 UTC, Dovid308 commented on src/3_PB/VerbaliEsterni/VerbaleEsterno_240320/content.typ
> +L'incontro ha preso avvio con una breve analisi del lavoro svolto dal precedente SAL, concentrato sull'implementazione dei test di unità all'interno del simulatore. Gli 11 sensori sviluppati nello sp
sincero mi sembra molto artificiale come costruzione della frase

2024-03-21 19:03 UTC, nance97 requested changes

2024-03-21 19:03 UTC, nance97 commented on src/3_PB/VerbaliEsterni/VerbaleEsterno_240320/content.typ
> +Considerando l'avvio del secondo lotto per il progetto didattico, la Proponente ha sollevato la necessità di rispettare gli impegni presi per garantire il completamento tempestivo. Ciò consentirebbe
```suggestion
Considerando l'avvio del secondo lotto per il progetto didattico, la Proponente ha sottolineato la necessità di rispettare le scadenze fissate precedentemente dal team per portare a termine il progetto nelle tempistiche previste. Ciò consentirebbe all'azienda di gestire efficacemente la candidatura dei nuovi gruppi, ormai molto vicina. Inoltre, è stato chiesto al team di preparare una breve valutazione del ruolo svolto dalla Proponente lungo il percorso che ha portato al completamento del progetto per individuare possibili miglioramenti e garantire un'esperienza ottimale ai nuovi gruppi. Ad esempio, la Proponente ha già deciso di interrompere l'utilizzo dell'applicazione Element a favore di Discord, considerato più diffuso e funzionale.
```

2024-03-21 19:03 UTC, nance97 commented on src/3_PB/VerbaliEsterni/VerbaleEsterno_240320/content.typ
> +È stato concordato di programmare il prossimo SAL per martedì 02/04/2024, con l'orario ancora da definire, direttamente presso la sede della Proponente. L'incontro vedrà la partecipazione di Andrea D
```suggestion
È stato concordato di programmare il prossimo SAL per martedì 02/04/2024, con l'orario ancora da definire, direttamente presso la sede della Proponente. L'incontro vedrà la partecipazione di Andrea Dorigo e il team punterà a ottenere l'approvazione formale per l'MVP, il che lo renderebbe l'ultimo incontro esterno.
```

2024-03-22 12:43 UTC, Dovid308 commented on src/3_PB/VerbaliEsterni/VerbaleEsterno_240320/content.typ
> +Considerando l'avvio del secondo lotto per il progetto didattico, la Proponente ha sollevato la necessità di rispettare gli impegni presi per garantire il completamento tempestivo. Ciò consentirebbe
fidati che sono 1 alla fine, ma poi è una cosa che hanno detto loro ?

2024-03-22 12:43 UTC, Dovid308 commented
@lonewalker0 come procede?

2024-03-23 10:14 UTC, Dovid308 submitted a review, later dismissed

2024-03-23 10:14 UTC, Dovid308 commented on src/3_PB/VerbaliEsterni/VerbaleEsterno_240320/content.typ
> +È stato concordato di programmare il prossimo SAL o per giovedì 28/03/2024 o per martedì 02/04/2024, con l'orario ancora da definire, direttamente presso la sede della Proponente. È nostra responsabi
```suggestion
Per il prossimo SAL sono state proposte le due date di giovedì 28/03/2024 e di martedì 02/04/2024, con orari ancora da definire, direttamente presso la sede della Proponente. È nostra responsabilità comunicare la nostra preferenza tramite mail. Tuttavia l'incontro di martedì 02/04/2024 vedrà la partecipazione di Andrea Dorigo, rendendolo preferibile. Durante tale incontro il team punta ad ottenere l'approvazione formale del prodotto realizzato come MVP, il che lo renderebbe, alla luce della preferenza espressa di non effettuare la fase CA, l'ultimo incontro esterno.
```

2024-03-23 10:14 UTC, Dovid308 commented on src/3_PB/VerbaliEsterni/VerbaleEsterno_240320/content.typ
> +L'incontro è iniziato con una breve analisi del lavoro svolto dal team dal precedente SAL, concentrato sull'implementazione dei test di unità dei simulatori e di integrazione dell'intero sistema nell
io ribadisco che secondo me questo paragrafo ha poco senso, magari teniamo solo il primo e l'ultimo periodo

2024-03-23 10:14 UTC, Dovid308 commented on src/3_PB/VerbaliEsterni/VerbaleEsterno_240320/content.typ
> +L'incontro è iniziato con una breve analisi del lavoro svolto dal team dal precedente SAL, concentrato sull'implementazione dei test di unità dei simulatori e di integrazione dell'intero sistema nell
```suggestion
L'incontro è iniziato con una breve analisi del lavoro svolto dal team dal precedente SAL, concentrato sull'implementazione dei test di unità dei simulatori e di integrazione dell'intero sistema nelle sue componenti. Entrambe le tipologie di test sono state effettuate con librerie apposite di Python: per la componente di simulazione sono state raggiunte una statement coverage e una branch coverage superiori all'80%.
```

2024-03-23 13:40 UTC, nance97 requested changes

2024-03-23 13:40 UTC, nance97 commented on src/3_PB/VerbaliEsterni/VerbaleEsterno_240320/content.typ
> +L'incontro è iniziato con una breve analisi del lavoro svolto dal team dal precedente SAL, concentrato sull'implementazione dei test di unità dei simulatori e di integrazione dell'intero sistema nell
sta bene anche a me, meno "verboso"

2024-03-23 13:40 UTC, nance97 commented on src/3_PB/VerbaliEsterni/VerbaleEsterno_240320/content.typ
> +È stato concordato di programmare il prossimo SAL o per giovedì 28/03/2024 o per martedì 02/04/2024, con l'orario ancora da definire, direttamente presso la sede della Proponente. È nostra responsabi
```suggestion
Per il prossimo SAL sono state proposte le due date di giovedì 28/03/2024 e di martedì 02/04/2024, con orari ancora da definire, direttamente presso la sede della Proponente. È nostra responsabilità comunicare la nostra preferenza tramite email. Tuttavia, l'incontro di martedì 02/04/2024 vedrebbe la partecipazione di Andrea Dorigo, e sarebbe quindi preferibile. Durante tale incontro, infatti, il team punta ad ottenere l'approvazione formale del prodotto software realizzato come MVP; alla luce della preferenza espressa dal team di non effettuare la terza revisione CA, si tratterebbe a tutti gli effetti dell'ultimo incontro esterno.
```

2024-03-24 13:17 UTC, merged