update pdq e ndp
SWATEngineering/Docs pull request #287
Opened 2024-03-20 21:31 UTC by Dovid308

aggiunti alle ndp procedure di testing integrazione,  e chiarificazione che test unità integrazione non saranno classificati nel pdp. 

tralaltro mi sono accorto di un problema nel changelog mi sono accorto di un problema nel chanegelog. 

Inoltre a sto  punto chiuderei senza segnare una mia  modifica nel changelog perchè comunque non ho ruolo di amministratore in questo sprint.

2024-03-21 19:16 UTC, nance97 requested changes

2024-03-21 19:16 UTC, nance97 commented on src/3_PB/NormeDiProgetto/content.typ
> +Test di sistema e di accettazione, e relativo stato, vengono riportati all'interno del documento _Piano di Qualifica v1.0_.
```suggestion
Test di sistema e di accettazione, e relativo stato, vengono riportati all'interno del documento _Piano di Qualifica v2.0_.
```

2024-03-21 19:16 UTC, nance97 commented on src/3_PB/NormeDiProgetto/content.typ
> +Per poter eseguire i test di unità in maniera automatica e ottenere la percentuale di copertura del codice si rimanda alla procedure presentate nella  @calcolo_metriche_affidabilita.
```suggestion
Per poter eseguire i test di unità in maniera automatica e ottenere la percentuale di copertura del codice si rimanda alle procedure presentate nella  @calcolo_metriche_affidabilita.
```

2024-03-21 19:16 UTC, nance97 commented on src/3_PB/NormeDiProgetto/content.typ
> +- Avviare i container con il profilo "dev";
dato che non viene mai menzionato nelle NdP come avviare i containers con docker compose up, aggiungerei che i comandi per avviare l'applicazione sono specificati nel readme di InnovaCity/nel Manuale Utente; così per sapere come fare

2024-03-21 19:16 UTC, nance97 commented on src/3_PB/NormeDiProgetto/content.typ
> +I test vengono identificati, all'interno del _Piano di Qualifica v1.0_, in base alla loro tipologia e tramite un codice numerico.
```suggestion
I test vengono identificati, all'interno del _Piano di Qualifica v2.0_, in base alla loro tipologia e tramite un codice numerico. 
```

2024-03-21 19:16 UTC, nance97 commented on src/3_PB/PianoDiQualifica/content.typ
> +- *Test di accettazione*: si verifica il soddisfacimento del Committente rispetto al prodotto software. Il loro superamento permette di procedere con il rilascio del prodotto.
```suggestion
- *Test di accettazione*: si verifica il soddisfacimento della Proponente rispetto al prodotto software. Il loro superamento permette di procedere con il rilascio del prodotto. 
```

2024-03-21 19:16 UTC, nance97 commented on src/3_PB/PianoDiQualifica/content.typ
> +Di seguito si presentano di conseguenza solamente test di sistema e test di accettazione.
mi ricordi come mai non vogliamo normarli? solo perchè al momento non hanno corrispondenza/sono presenti all'interno del PdQ?

2024-03-22 12:28 UTC, Dovid308 commented on src/3_PB/PianoDiQualifica/content.typ
> +Di seguito si presentano di conseguenza solamente test di sistema e test di accettazione.
come abbiamo stabilito adesso rimuovo

2024-03-22 12:29 UTC, Dovid308 commented on src/3_PB/NormeDiProgetto/content.typ
> +- Avviare i container con il profilo "dev";
sai che non saprei, di certo non dobbiamo proprio specificare qualsiasi cosa nelle norme di progetto, ci sono delle cose che per forza sono lasciate a noi

2024-03-23 09:58 UTC, Dovid308 commented on src/3_PB/NormeDiProgetto/content.typ
> +- Avviare i container con il profilo "dev";
le norme sono un documento interno

2024-03-23 13:29 UTC, nance97 approved these changes

2024-03-23 13:51 UTC, lonewalker0 approved these changes

2024-03-23 13:51 UTC, merged