271 normare diagrammi database NdP
SWATEngineering/Docs pull request #296
Opened 2024-03-22 17:20 UTC by simocare

2024-03-25 09:55 UTC, lonewalker0 requested changes

2024-03-25 09:55 UTC, lonewalker0 commented on src/3_PB/NormeDiProgetto/content.typ
> +Per quanto riguarda la progettazione del database, i Progettisti devono definire lo schema delle tabelle che andranno a costituire il database del #glossary[sistema]. Questo schema deve essere rappre
```suggestion
Per quanto riguarda la progettazione del database, il Progettista deve definire lo schema delle tabelle che vanno a costituire il database del #glossary[sistema]. Questo schema deve essere rappresentato attraverso un diagramma che mostri le tabelle coinvolte, i campi che le compongono e le relazioni tra di esse. Essendo che il database è contenuto in un DBMS di tipo OLAP, uno schema ER classico non era adatto a rappresentarlo; pertanto, si è scelto di definire una rappresentazione alternativa, che permettesse di visualizzare in modo chiaro e conciso le tabelle e le relazioni tra di esse.
```

2024-03-25 09:55 UTC, lonewalker0 commented on src/3_PB/NormeDiProgetto/content.typ
> +        - *engine*: indica il motore di database utilizzato per la creazione della tabella; viene riportato anch'esso all'interno di un "post it", posto nei pressi della tabella.
```suggestion
        - *Tabella*: rappresenta una tabella del database e viene rappresentata con un rettangolo a linea piena, separando con una linea il nome della tabella, i nomi degli attributi e i tipi di dato;
        - *#glossary[Materialized views]*: rappresenta una vista materializzata, ovvero una tabella che contiene i risultati di una query; viene rappresentata con un rettangolo a linea tratteggiata;
        - *Query*: rappresenta una query SQL, viene riportata all'interno di un "post it" collegato alla #glossary[materialized views] a cui fa riferimento;
        - *Flusso dei dati*: rappresenta il flusso di dati tra le tabelle e le #glossary[materialized views], viene rappresentato con una freccia piena;
        - *Riferimento*: viene utilizzata per collegare un "post it" con la #glossary[materialized views] a cui fa riferimento; si rappresenta con una freccia tratteggiata;
        - *Engine*: indica il motore di database utilizzato per la creazione della tabella; viene riportato anch'esso all'interno di un "post it", posto nei pressi della tabella.
```

2024-03-25 09:58 UTC, Dovid308 commented
ho risolto il conflitto del changelog, inoltre ci sarebbe da cambiare il nome del documento specifice tecnoche in specifica tecnica

2024-03-25 10:02 UTC, Dovid308 commented
dico in generale nelle ndp

2024-03-25 20:45 UTC, Dovid308 approved these changes

2024-03-25 20:48 UTC, Dovid308 submitted a review, later dismissed

2024-03-25 20:48 UTC, Dovid308 commented
@lonewalker0 quando vuoi per me mergiabile

2024-03-26 08:52 UTC, lonewalker0 requested changes

2024-03-26 08:52 UTC, lonewalker0 commented on src/3_PB/NormeDiProgetto/changelog.csv
> +1.4,21-03-2024,Normati Diagrammi del database, "Simone Caregnato",Amministratore,"Giacomo D'Ovidio"
```suggestion
1.4,21-03-2024,Normati Diagrammi del database, "Simone Caregnato",Amministratore,"Giacomo D'Ovidio, Riccardo Costantin"
```

2024-03-26 10:08 UTC, lonewalker0 approved these changes

2024-03-27 11:05 UTC, merged