Aggiungere MU a NdP
SWATEngineering/Docs pull request #304
Opened 2024-03-26 10:10 UTC by nance97

2024-03-26 11:24 UTC, lonewalker0 requested changes

2024-03-26 11:24 UTC, lonewalker0 commented on src/3_PB/NormeDiProgetto/content.typ
> +Il _Manuale Utente_, redatto dal Programmatore, è un documento essenziale che fornisce agli utenti finali tutte le informazioni necessarie per utilizzare in modo efficace il software. Tale documento
```suggestion
Il _Manuale Utente_, redatto dal Programmatore, è un documento essenziale che fornisce agli utenti finali tutte le informazioni necessarie per utilizzare in modo efficace il prodotto. Tale documento è progettato per essere una risorsa completa che accompagna l'utente lungo tutto il processo di utilizzo del software, dalla fase di installazione fino alla gestione quotidiana delle funzionalità offerte.
```

2024-03-26 13:01 UTC, lonewalker0 approved these changes

2024-03-27 11:19 UTC, simocare requested changes
Prima di mergiare:
- eseguire un rebase;
- aggiornare il changelog.

2024-03-27 11:19 UTC, simocare commented on src/3_PB/NormeDiProgetto/content.typ
> +        - *Requisiti minimi*: fornisce informazioni riguardanti le specifiche hardware, software, di #glossary[sistema] operativo e browser necessarie per eseguire correttamente il programma;
```suggestion
        - *Requisiti minimi*: fornisce informazioni riguardanti le specifiche hardware, software, di sistema operativo e browser necessarie per eseguire correttamente il programma;
```

2024-03-28 14:10 UTC, nance97 commented
> Prima di mergiare:
> 
> * eseguire un rebase;
> * aggiornare il changelog.

fatto!

2024-03-28 14:35 UTC, simocare approved these changes

2024-03-28 14:35 UTC, merged