Aggiunta consunitvo sprint 13 + ricalcolo preventivo sprint 14
SWATEngineering/Docs pull request #305
Opened 2024-03-26 10:26 UTC by RiccardoTonioloDev

2024-03-26 11:12 UTC, nance97 requested changes
Deve essere aggiornata anche la pianificazione dello sprint 14, propongo:

- Terminare la stesura del _Piano di Progetto_:
    - Aggiornare pianificazione e preventivo pertinenti allo #glossary[sprint] 14 e inserire il consuntivo pertinente allo #glossary[sprint] 13;
    - Trattandosi dell'ultimo #glossary("sprint"), inserire anche il consuntivo dello #glossary[sprint] 14 al termine dello stesso;
- Aggiornare il _Manuale Utente_ con:
    - Aggiungere le API key necessarie per il corretto funzionamento del software alla sezione riguardante l'installazione;
    - Aggiungere una sezione riguardante la componente di allarmistica su Discord;
    - Aggiungere screenshot rilevanti.
- Terminare la stesura del _Piano di Qualifica_ con l'aggiornamento di tutte le metriche;
- Raffinare l'aspetto estetico delle #glossary[dashboard] finali in #glossary[Grafana] e inserire un numero adeguato di sensori con locazioni realistiche, prima di presentare il software alla Proponente per la validazione del prodotto come #glossary[MVP];
- Revisione in stile #glossary("walkthrough") dei documenti e relativa approvazione;
- Presentare la candidatura alla prima fase della seconda revisione #glossary("PB") e preparare la relativa presentazione.

2024-03-26 11:13 UTC, nance97 commented
bisognerebbe anche togliere ogni menzione della CA visto che non la faremo ma posso farlo io quando metterò mano nuovamente al PdP per fare una somma delle ore e il preventivo finale.

2024-03-26 11:38 UTC, lonewalker0 requested changes

2024-03-26 11:38 UTC, lonewalker0 commented on src/3_PB/PianoDiProgetto/sections/ConsuntivoSprint/TredicesimoSprint.typ
> +Durante lo #glossary[sprint] attuale, l'unico rischio che si è manifestato è stato il rischio RT1 - Conoscenze tecnologiche limitate. Questa iterazione ha visto come problema principale l'implementaz
```suggestion
Durante lo #glossary[sprint] attuale, l'unico rischio che si è manifestato è stato il rischio RT1 - Conoscenze tecnologiche limitate. Questo #glossary[sprint] ha visto come problema principale l'implementazione del sistema di notifiche del prodotto il quale, è risultato particolarmente complesso da gestire e configurare secondo le specifiche desiderate. Tuttavia,  grazie a una stretta collaborazione tra Programmatori,  è stato possibile superare tale ostacolo.
```

2024-03-26 11:41 UTC, lonewalker0 requested changes

2024-03-26 11:41 UTC, lonewalker0 commented on src/3_PB/PianoDiProgetto/sections/ConsuntivoSprint/TredicesimoSprint.typ
> +È rilevabile un distacco di un 13% tra le ore preventivate e quelle consuntivate, questo però dovuto non ad una mancanza di lavoro da parte del team, bensì ad una pianificazione troppo pessimista, in
metterei qualcos'altro al posto di troppo pessimista

2024-03-28 10:00 UTC, RiccardoTonioloDev commented on src/3_PB/PianoDiProgetto/sections/ConsuntivoSprint/TredicesimoSprint.typ
> +È rilevabile un distacco di un 13% tra le ore preventivate e quelle consuntivate, questo però dovuto non ad una mancanza di lavoro da parte del team, bensì ad una pianificazione troppo pessimista, in
Più pessimista del necessario?

2024-03-28 10:00 UTC, RiccardoTonioloDev commented
> Deve essere aggiornata anche la pianificazione dello sprint 14, propongo:
> 
> * Terminare la stesura del _Piano di Progetto_:
>   
>   * Aggiornare pianificazione e preventivo pertinenti allo #glossary[sprint] 14 e inserire il consuntivo pertinente allo #glossary[sprint] 13;
>   * Trattandosi dell'ultimo #glossary("sprint"), inserire anche il consuntivo dello #glossary[sprint] 14 al termine dello stesso;
> * Aggiornare il _Manuale Utente_ con:
>   
>   * Aggiungere le API key necessarie per il corretto funzionamento del software alla sezione riguardante l'installazione;
>   * Aggiungere una sezione riguardante la componente di allarmistica su Discord;
>   * Aggiungere screenshot rilevanti.
> * Terminare la stesura del _Piano di Qualifica_ con l'aggiornamento di tutte le metriche;
> * Raffinare l'aspetto estetico delle #glossary[dashboard] finali in #glossary[Grafana] e inserire un numero adeguato di sensori con locazioni realistiche, prima di presentare il software alla Proponente per la validazione del prodotto come #glossary[MVP];
> * Revisione in stile #glossary("walkthrough") dei documenti e relativa approvazione;
> * Presentare la candidatura alla prima fase della seconda revisione #glossary("PB") e preparare la relativa presentazione.

Ma sei un amore

2024-03-28 14:17 UTC, nance97 approved these changes

2024-03-28 14:20 UTC, merged