315 Update versione NdP
SWATEngineering/Docs pull request #318
Opened 2024-04-14 12:09 UTC by nance97

2024-04-15 15:23 UTC, Dovid308 commented
Credo che gran parte delle modifiche post RTB siano mie, tue e di simone, ci vorrebbe un occhio esterno magari.

2024-04-18 07:34 UTC, lonewalker0 requested changes
programmatore ruolo:
ampliamento delle specifiche tecniche andrebbe spostato su progettista

2024-04-18 07:39 UTC, lonewalker0 requested changes
ricontrollando andrebbe messo estimate to completion e estimate at completion senza la d finale

2024-04-18 07:40 UTC, lonewalker0 requested changes
paragrafo calcolo metriche codifica:
può è senza l'accento

2024-04-18 07:41 UTC, lonewalker0 submitted a review, later dismissed
anche su calcolo metriche affidabilità può è senza l'accento

2024-04-18 13:33 UTC, nance97 commented
per me si può mergiare

2024-04-18 14:40 UTC, Dovid308 approved these changes
non ho guardato ma mi viene confermato che va bene

2024-04-18 14:40 UTC, merged