Stesura iniziale
SWATEngineering/Docs pull request #79
Opened 2023-11-27 21:51 UTC by lonewalker0

2023-11-28 19:49 UTC, nance97 commented on src/2_RTB/PianoDiQualifica/content.typ
> +          - Gestione dei Difetti e delle Anomalie riscontrate durante le attività di verifica;
- ";" dopo "...la valutazione dei risultati";
- difetti e anomalie?

2023-11-28 19:52 UTC, nance97 commented on src/2_RTB/PianoDiQualifica/content.typ
> +Si riferisce all'efficacia ed efficienza dei processi e delle metodologie impiegate nello sviluppo, testing e mantenimento del software. Essa abbraccia l'insieme di attività, pratiche e metodi utiliz
e entro --> ed entro

2023-11-28 20:00 UTC, nance97 commented on src/2_RTB/PianoDiQualifica/content.typ
> +  - *SPI*: _Schedule Performance Index_ Misura l'efficienza del tempo rispetto alla pianificazione;
manterrei la formattazione precedente in cui la prima lettera della parola dopo il corsivo rimane minuscola per questo e i punti successivi

2023-11-28 20:01 UTC, nance97 commented on src/2_RTB/PianoDiQualifica/content.typ
> +  - *SPI*: _Schedule Performance Index_ Misura l'efficienza del tempo rispetto alla pianificazione;
cosa si intende con l'efficienza del tempo?

2023-11-28 20:03 UTC, nance97 commented on src/2_RTB/PianoDiQualifica/content.typ
> +  - *EAC*: _Estimated at Completion_ Stima del costo totale previsto per completare il progetto;
definizione molto simile a quella del BAC sopra, che differenza c'e' tra i due?

2023-11-28 20:18 UTC, nance97 commented on src/2_RTB/PianoDiQualifica/content.typ
> +        - Formula: $"BV" = "PV" - "AC"$.
- manca lo spazio tra abbreviazione e termine completo in corsivo;
- a quale _baseline_ ti riferisci?
- per BV direi "..si è speso più o di meno rispetto a quanto inizialmente previsto nel budget." con punto alla fine visto che e' l'ultimo punto.

2023-11-28 20:20 UTC, nance97 commented on src/2_RTB/PianoDiQualifica/content.typ
> +*Leggenda*:
Legenda

2023-11-28 20:22 UTC, nance97 commented on src/2_RTB/PianoDiQualifica/content.typ
> +Sono state individuate 2 metriche principali:
due

2023-11-28 20:24 UTC, nance97 commented on src/2_RTB/PianoDiQualifica/content.typ
> +                  - *_Significato_*:Un fan-out elevato può indicare che un modulo ha molte dipendenze da altri moduli. Questo può portare a una maggiore complessità del sistema, poiché le modifiche i
- manca spazio tra termine in grassetto e testo a seguire;
-  funzione specifica.; --> funzione specifica;

2023-11-28 20:35 UTC, nance97 commented on src/2_RTB/PianoDiQualifica/content.typ
> +      - *Rapporto di churn del codice*: Indica la frequenza con cui le linee di codice sono modificate nel tempo, fornendo informazioni sulla stabilità del codice e sulla necessità di frequenti modif
misura, indica per seguire la formattazione corrente

2023-11-28 20:36 UTC, nance97 commented on src/2_RTB/PianoDiQualifica/content.typ
> +      - *IG* _Indice Gulpease_ metrica utilizzata per valutare la leggibilità di un testo in lingua italiana.
IG:

2023-11-28 20:37 UTC, nance97 requested changes
non e' stato eseguito il check per la compilazione automatica.

2023-11-29 08:31 UTC, lonewalker0 commented on src/2_RTB/PianoDiQualifica/content.typ
> +          - Gestione dei Difetti e delle Anomalie riscontrate durante le attività di verifica;
> * difetti e anomalie?

i bug

2023-11-29 08:41 UTC, lonewalker0 commented on src/2_RTB/PianoDiQualifica/content.typ
> +  - *EAC*: _Estimated at Completion_ Stima del costo totale previsto per completare il progetto;
L' EAC è un BAC rivisto allo stato corrente del progetto.

2023-11-29 09:06 UTC, lonewalker0 commented on src/2_RTB/PianoDiQualifica/content.typ
> +  - *SPI*: _Schedule Performance Index_ Misura l'efficienza del tempo rispetto alla pianificazione;
Fornisce un indicatore numerico che rappresenta il rapporto tra il lavoro effettivamente eseguito (o il valore guadagnato) e il lavoro pianificato fino a un determinato punto nel tempo.  Aiuta a valutare quanto il progetto sta rispettando il programma pianificato

2023-11-29 13:32 UTC, nance97 approved these changes

2023-11-29 13:40 UTC, nance97 requested changes
aggiungere termine _deliverable_ a Glossario all'interno del branch corrente.

2023-11-30 08:55 UTC, nance97 approved these changes

2023-11-30 08:55 UTC, merged