Verbaleinterno2411
SWATEngineering/Docs pull request #82
Opened 2023-11-28 21:02 UTC by Dovid308

close #55

2023-11-30 08:09 UTC, nance97 commented on src/2_RTB/VerbaliInterni/VerbaleInterno_241123/content.typ
> +- Programmatore: Simone Caregnato;
";" --> "." alla fine

2023-11-30 08:19 UTC, nance97 commented on src/2_RTB/VerbaliInterni/VerbaleInterno_241123/content.typ
> +Si precisa che il cambio dei ruoli è opzionale e non necessariamente riguarda la totalità dei ruoli e dei membri.
- "Per favorire una rotazione più rapida e un carico di lavoro distribuito in modo più omegeneo il team ha deciso di introdurre la possibilità di cambiare i ruoli una volta raggiunta la metà temporale di ogni sprint."
- venerdi --> venerdi'
- dopo l'ultima frase aggiungerei il criterio secondo cui cambiamo i ruoli, ossia il fatto che e' legato al completamento e verifica delle issues assegnate a un determinato ruolo: se qualcuno ha esaurito le proprie issues e' libero di assumersi un altro ruolo, altrimenti mantiene lo stesso ruolo e continua a lavorare alle issues non terminate.

2023-11-30 08:42 UTC, nance97 commented on src/2_RTB/VerbaliInterni/VerbaleInterno_241123/content.typ
> +Sulla base della somma delle dimensione delle _issues_ selezionate il nuovo sprint risulta decisamente più corposo di quello precedente.
Sulla base della somma delle dimensioni...

2023-11-30 08:50 UTC, nance97 commented on src/2_RTB/VerbaliInterni/VerbaleInterno_241123/content.typ
> +Il Processo di selezione delle _issues_ si è basato sull'obiettivo dello sprint rilevato con la Proponente, ovvero il completamente del PoC: ciò nonostante non si può dire che lo sprint sia univocame
- Questo è in linea con l'intenzione di effettuare la revisione _RTB_ in data 18 dicembre, --> direi piu' che vorremmo preparare tutto l'occorrente per poter richiedere la prima revisione RTB non oltre il 18 perche' non la effettueremo esattamente quel giorno; e "." alla fine della frase;
- rimuoverei " L'idea è di dedicare ora maggiore impegno per raggiungere gli obiettivi prefissati, anche a costo di rallentare il ritmo nel prossimo sprint."
- sull'obiettivo dello sprint --> sugli obiettivi dello sprint rilevati
- completamente --> completamento di una prima versione del PoC;
- aggiungerei all'ultimo pezzo dopo il ":" focalizzato su di esso, in quanto il team si impegnera' anche a portare avanti la stesura della parte documentale relativa al RTB.

2023-11-30 08:52 UTC, nance97 requested changes
Revisionato verbale interno.

2023-12-01 08:58 UTC, nance97 requested changes
Piccolo fix al verbale interno.

2023-12-01 15:35 UTC, Dovid308 commented on src/2_RTB/VerbaliInterni/VerbaleInterno_241123/content.typ
>  Inizialmente si sono rilevate le nuove issue a seguito dell'incontro con la proponente avvenuto la mattinata stessa e sono state inserite nel _Product Backlog_.
ho lasciato al termine dell'incotro e basta. perchè effettivamente non è cronologicamente avvenuto dopo l'incontro con la proponente piuttosto al termine del nostro incontro interno;

2023-12-01 15:57 UTC, nance97 approved these changes

2023-12-01 15:57 UTC, merged