78 pdp pianificazione
SWATEngineering/Docs pull request #99
Opened 2023-12-01 15:27 UTC by Dovid308

close #57 close #78

2023-12-02 11:31 UTC, nance97 reviewed
@lonewalker0 ho modificato le sezioni Pianificazione, Preventivo e Consuntivo con i dati pertinenti ai primi due sprint; i calcoli per i grafici/tabelle li ho fatti utilizzando il foglio Areogrammi su Drive se vuoi dare un'occhio/apportare modifiche. Ora bisogna pensare a come procedere oltre l'RTB.

2023-12-07 08:13 UTC, lonewalker0 commented
inserisco stasera il changelog

2023-12-07 08:17 UTC, nance97 commented on src/2_RTB/PianoDiProgetto/sections/AnalisiDeiRischi.typ
> +
- nel secondo punto, Responsabile e Amministratore
- manca la menzione del fatto che usiamo il sistema di revisione/verifica per arginare il rallentamento causato dal context switch/cold start, della serie le prime modifiche apportate dal componente che occupa il nuovo ruolo vengono revisionate dal componente che lo occupava in precedenza

2023-12-08 11:06 UTC, simocare requested changes

2023-12-08 13:53 UTC, lonewalker0 commented on src/2_RTB/PianoDiProgetto/sections/Consuntivo.typ
> +Si riportano inoltre gli elementi positivi e negativi emersi all'interno delle retrospettive di ogni sprint, eventuali rischi incorsi e la valutazione del relativo processo di mitigazione, in modo ta
proverei a mettere un riferimento alla sezione quà, il problema è che si trova in un altra pagina .typ e

2023-12-08 14:09 UTC, lonewalker0 commented on src/2_RTB/PianoDiProgetto/sections/ModelloDiSviluppo.typ
> +Non ci si concetra sul prodotto ma piuttosto sul _way of working_.
ci si concentra maggiormente sull'organizzazione, invece del prodotto, che lo revisiona la proponente

2023-12-08 22:40 UTC, lonewalker0 commented on src/2_RTB/PianoDiProgetto/sections/PianificazioneSprint/DodicesimoSprint.typ
> +              + Parcheggi nelle celle;
avevamo ipotizzato che la mappa fosse divisa in celle, con i vari sensori parcheggio

2023-12-08 22:45 UTC, lonewalker0 commented on src/2_RTB/PianoDiProgetto/sections/PianificazioneSprint/NonoSprint.typ
> +  - Certificati di sicurezza per la comunicazione dati? [Revisore]
più che altro se aveva senso aggiungere la protezioni dati con qualche protocollo  nella trasmissioni dati

2023-12-08 22:47 UTC, lonewalker0 commented on src/2_RTB/PianoDiProgetto/sections/PianificazioneSprint/NonoSprint.typ
> +  - Impostazione della dimensione del batch e l'intervallo di invio per ottimizzazione latenza ed efficienza;
perché efficienza nel glossario?

2023-12-08 23:07 UTC, lonewalker0 commented on src/2_RTB/PianoDiProgetto/sections/PianificazioneSprint/UndicesimoSprint.typ
> +    - Divisione in celle della città;
poco chiaro cosa intendi

2023-12-10 11:02 UTC, simocare requested changes

2023-12-10 11:02 UTC, simocare commented on src/2_RTB/PianoDiProgetto/sections/PianificazioneSprint/UndicesimoSprint.typ
> +    - Divisione in celle della città;
Tu intendevi suddivisione della mappa?

2023-12-10 11:22 UTC, simocare commented on src/2_RTB/PianoDiProgetto/sections/PianificazioneSprint/NonoSprint.typ
> +  - Impostazione della dimensione del batch e l'intervallo di invio per ottimizzazione latenza ed efficienza;
Perché è un termine di cui Vardanega ci ha dato una definizione precisa e ho pensato che si poteva riportarla.

2023-12-10 12:02 UTC, lonewalker0 commented on src/2_RTB/PianoDiProgetto/sections/PianificazioneSprint/UndicesimoSprint.typ
> +    - Divisione in celle della città;
si suddividevi la mappa in celle e su queste visualizzavi i sensori

2023-12-10 14:04 UTC, simocare commented on src/2_RTB/PianoDiProgetto/sections/PianificazioneSprint/UndicesimoSprint.typ
> +    - Divisione in celle della città;
Ok, dovremo capire se utilizzeremo il termine "cella" per riferirci a questo, che in caso lo aggiungo al glossario.
Intanto se ti va bene, ti ho suggerito una modifica.

2023-12-11 14:31 UTC, lonewalker0 commented
bro non posso fare review di quello che ho scritto io

2023-12-11 15:25 UTC, simocare approved these changes

2023-12-11 15:25 UTC, merged